### ISSUE TITLE
Any plans to support Github Enterprise?

### ISSUE THREAD

**Issue by perrupa** [pullapprove/support#1]
Managing approvals on Github Enterprise can be tedious, trying to keep track of all the _thumbs-up_ in the comments, whether they're still relevant or if too much has changed since.

Any plans to support Github Enterprise?

**Comment by davegaeddert** [comment]
Hey @perrupa, I wasn't planning on GitHub Enterprise being an immediate next step, but it certainly could be if people wanting it. We don't use Enterprise ourselves, so I'll have to look into this a little bit. Are there other services that you think do a good job of integrating with GitHub Enterprise?

If anybody else is looking for GitHub Enterprise support, make a comment!

**Comment by perrupa** [comment]
[Jira's DVCS plugin](https://marketplace.atlassian.com/plugins/com.atlassian.jira.plugins.jira-bitbucket-connector-plugin) is not bad at all and there's the [Github pull request builder](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin).

Not sure if that's enough to help ya though.

**Comment by adamschnaare** [comment]
I'd be interested in seeing some GitHub Enterprise support. A client I'm working with is using GHE presently, and this would potentially fit a big need we have in moving away from some more process-heavy solutions to approving code in GHE

**Comment by davegaeddert** [comment]
Hey @adamschnaare, thanks for mentioning something. I've started a conversation with GitHub to learn more about what that entails -- admittedly, I've never used GHE. Do you have any examples of services that do GHE integration well?

**Comment by gtallen1187** [comment]
I would also be interested in GitHub Enterprise support.

[ZenHub](https://zenhub.io) has a nice enterprise setup, might serve as a nice example.

**Comment by adamschnaare** [comment]
@davegaeddert - sorry for the delay. Yeah, I'm not sure myself of any great examples. I recently started using it for a client. I'm just looking around for uses that would be helpful for them, hence the comment on  this repo.

**Comment by unicman** [comment]
+1. looking for enterprise support.

**Comment by jmcshane** [comment]
+1 for enterprise support. This plugin would work well with our workflow if it was available.

**Comment by davegaeddert** [comment]
Happy to announce that we now have a PullApprove Enterprise product! Just email us at enterprise@pullapprove.com if you're interested.

cc: @perrupa @adamschnaare @gtallen1187 @unicman @jmcshane

**Comment by adamschnaare** [comment]
Thanks @davegaeddert ! Passing along this to the stakeholders in our organization.
