### ISSUE TITLE
Wrong team being used for reviews

### ISSUE THREAD

**Issue by caniszczyk** [pullapprove/support#100]
In this review: https://pullapprove.com/opencontainers/runtime-spec/pull-request/589/reviews/

'cyphar' isn't a valid reviewer here. He's not part of the 'runtime-spec-maintainers' team, however he is part of the 'runc-maintainers' team, could it be PullApprove is confused?

**Comment by davegaeddert** [comment]
Sure enough -- I ran "sync" on the runtime-spec-maintainers team and he was removed. Has he ever been a part of that team? Or should I dig in further and see if pullapprove associated him there by mistake?

**Comment by caniszczyk** [comment]
@davegaeddert he may have been part of that team but it was a long time ago, or he was potentially part of another team that was part of that repo but was then removed

I'm not too concerned about this issue but it does catch you by surprise, up to you if you want to dig further :)

**Comment by caniszczyk** [comment]
@davegaeddert thanks again for the super quick turn around!

**Comment by davegaeddert** [comment]
@caniszczyk sounds good, thanks for bringing it to my attention ;)
