### ISSUE TITLE
After removal from a team, I still appear as a reviewer

### ISSUE THREAD

**Issue by alexeagle** [pullapprove/support#105]
Yesterday morning I was removed from team 
https://github.com/orgs/angular/teams/repoowners
Today I sent a pull request which triggers a review by that team, and I still appear as a reviewer:
https://pullapprove.com/angular/angular/pull-request/13899/reviews/

is something cached? Would a user who has been removed from a team actually be able to approve a change that requires membership in that team?

**Comment by davegaeddert** [comment]
My guess is that you ran into this: https://github.com/pullapprove/support/issues/33

We don't currently use the organization webhooks, which is where changes to the team come from. We do periodically sync teams based on a few other events, but currently it looks like we use a repo "admin" token to do that -- which there's probably not one based on how you described setting up the bot user. There are a couple other places not having an "admin" token could create an issue -- I think setting up the webhooks for pullapprove is one but yours should already be configured from when that user _did_ have admin access.

We'll take a look to see if the team syncing can be done using a user with "push" permission, assuming your bot user has push/write access?

I triggered the re-sync on that PR from the backend, so it should be up-to-date now.

**Comment by alexeagle** [comment]
The bot user does have write access to the repo (I think this is required for you to update PR statuses).
But it does not have admin access. It would be great if your sync could work without it.
I see where we could sync the teams list ourselves at https://pullapprove.com/angular/angular/settings/ - I'll note that in our docs.
Thanks!

/cc @IgorMinar

**Comment by davegaeddert** [comment]
Yeah we'll take a look. A lot of the original code was built around the assumption that there'd be at least one admin token to use. You can run into all kinds of weird scenarios with "secret" teams and stuff where sometimes you need a fairly high level of access to get all the data.

We did actually check with GitHub on the new integrations system, but they weren't able to provide any timeline on that. But we're anxious to redesign some of these things with a simpler flow!

Let me know if you have any other questions.

**Comment by davegaeddert** [comment]
@alexeagle after a quick check, doesn't look like we can get the list of teams with the bot user's token. I can get the /collaborators endpoint using the bot's token, but not /teams.

I cut the token out of the image but you can see a quick test of the results here:

![image](https://cloud.githubusercontent.com/assets/649496/21908516/a86415ac-d8d9-11e6-99bc-a49cd0ef8320.png)
![image](https://cloud.githubusercontent.com/assets/649496/21908546/beb63bf0-d8d9-11e6-8703-fbd8d502f415.png)
