### ISSUE TITLE
Is it possible to select which branches to apply pull approve to using a regex or partial string match?

### ISSUE THREAD

**Issue by dxinteractive** [pullapprove/support#106]
We've recently moved to using a release branch structure, and it would be great to apply pullapprove to any branches whose branch names start with `release/`. Is this possible? If not, would this feature be considered?

**Comment by davegaeddert** [comment]
Good question. Currently we don't support regex for the branch conditions, but we certainly could (and should). I think this definitely makes sense to do. Can't give you a definite time frame on it, but we'll post any updates on this issue. Thanks!

**Comment by dxinteractive** [comment]
Awesome, thanks for this!

**Comment by jmvanryn** [comment]
+1  I would really like this...  is there a work around for now?

**Comment by davegaeddert** [comment]
Hey @jmvanryn, maybe one workaround for the time being would be to put a label on those PRs, and use that for pullapprove?

**Comment by davegaeddert** [comment]
The new PullApprove v3 lets you use fnmatch or regular expressions for branch conditions. We're still adding examples to the docs, but you can find more info here: https://www.pullapprove.com/docs/config/conditions/

One example:
```yaml
conditions:
- "'feature/*' in head.ref"
```
