### ISSUE TITLE
When a Reviewer Group has one member, and that member creates a PR, and PA is set to ignore author approval, the PR is always rejected

### ISSUE THREAD

**Issue by jonahwh** [pullapprove/support#107]
How to reproduce:

* Create a repo with a reviewer group (maybe it needs two, the second one can be in any configuration)
* Require that reviewer group to approve PRs
* Add **1** user to that reviewer group
* Ensure author approval is off
* Have the user in that reviewer group create a PR
* The PR is now always going to be rejected, because
  * The reviewer group **must** approve the PR, but
  * The reviewer cannot approve the PR, since author approval is off

Perhaps if a user is the only user in a group, the author approval setting should be ignored for that group?

**Comment by davegaeddert** [comment]
Author approval has changed a little bit in v3 and I'm not sure this is an issue anymore. More about the new `author_value` setting here: https://www.pullapprove.com/docs/config/reviews/
