### ISSUE TITLE
PullApprove daily update emails fails to show apostrophe

### ISSUE THREAD

**Issue by caglar10ur** [pullapprove/support#108]
They rendered as following instead of ' on MacOS Mail App

```
Open PR&apos;s to Review
```

and 

```
Your Open PR&apos;s
```

screenshots attached

![screenshot 2017-02-14 10 02 07](https://cloud.githubusercontent.com/assets/205498/22942060/c6d9de68-f29c-11e6-8a68-54ca644dccf8.png)

![screenshot 2017-02-14 10 03 13](https://cloud.githubusercontent.com/assets/205498/22942076/d5224f5a-f29c-11e6-9c48-b09db8f8e2fe.png)

**Comment by davegaeddert** [comment]
Well that's annoying. Thanks @caglar10ur.

**Comment by tripleee** [comment]
This seems to be fixed in the HTML rendering (though the HTML encoding is still bleeding through to the text/plain part; see also https://github.com/pullapprove/support/issues/112). Close this ticket, maybe?

**Comment by davegaeddert** [comment]
We'll be sure to get the email templates right for PullApprove v3 (https://www.pullapprove.com) 😉
