### ISSUE TITLE
Can it be configured so that PR can't be approved by it's author?

### ISSUE THREAD

**Issue by danilaml** [pullapprove/support#11]
So there won't be self-approved PRs.

**Comment by davegaeddert** [comment]
Hey @danilaml, we don't have a _specific_ setting for that yet, but have definitely been thinking about it and it would be pretty easy for us to add. One of the reasons we don't have that yet is because most people can accomplish what they need with the custom `.pullapprove.yml` settings that we already provide. It doesn't cover every scenario but I'd be curious if it would accomplish what you need -- you can read a little more about it here: http://docs.pullapprove.com/yaml/

Let me know if that would handle it or not. If not, a specific author setting would be something we could probably add pretty quickly!

**Comment by danilaml** [comment]
@davegaeddert the only way I see how to implement something like this now is to only increase number of required approvals and add additional reviewer which is not ideal solution (especially for a small project).

I think this option can be combined with https://github.com/pullapprove/support/issues/4
since they are "opposite". There could be option controlling behaviour regarding author approval - always or never or "forbidden" (need some better word) for example.

**Comment by davegaeddert** [comment]
Yeah that's what I was thinking as well, I had a hard time coming up with the wording too but my last thought was something like the following:

For your situation, where the author does not count towards approval:

``` yaml
author_approval: disabled  # or "ignored"?
```

The normal behavior:

``` yaml
author_approval: enabled
```

What #4 is about, where the author automatically approves it:

``` yaml
author_approval: auto
```

Kind of like #4, but saying that for this PR to pass approval the author _must_ manually approve it. The main use case I see for this is when people open PR's when they actually start the work -- "WIP" basically.

``` yaml
author_approval: required
```

I don't want to overcomplicate it too much right off the bat, but maybe we could start with "enabled" and "disabled". Thoughts? Do you want to provide an example `.pullapprove.yml` that shows the other settings that you'd use along with it so I have a better idea of your situation (how many reviewers, are there groups, etc.)?

**Comment by danilaml** [comment]
@davegaeddert we started using pullaprove before .yml file was a thing =)
Our use case is as follows:
we have two people that can review and 1 required review for PR.
The problem is that sometimes reviewer may push PR that isn't completely tested or reviewed by someone else. And we can't increase number of required reviews to 2 because one of the reviewers is sometimes absent for a notable period of time (weeks+).

**Comment by davegaeddert** [comment]
@danilaml I think this is almost ready to go! We'll do just a tad more testing after the holidays, then let you check it out.

**Comment by davegaeddert** [comment]
@danilaml I think this is ready for you to try. You'll need to add a `.pullapprove.yml` file to your repo -- it should be fairly straightforward, there's some docs here: http://docs.pullapprove.com/yaml/

I haven't added the `author_approval` to the docs yet, but for your case you'll just need to add a line:

``` yaml
author_approval: ignored
```

The other possible values are `default` and `required` (I cut out the `auto` for now). Let me know how it goes and if you have questions! If you want to get specific to your repo and not talk about it here, just use Intercom in the bottom right corner of the site.

**Comment by davegaeddert** [comment]
This has been officially added and initially documented here: http://docs.pullapprove.com/yaml/author_approval/
