### ISSUE TITLE
Please add a new fixes_issue requirement

### ISSUE THREAD

**Issue by jodh-intel** [pullapprove/support#110]
Currently, the only requirement that is supported is `signed_off_by`. This is very useful, but we'd like to also require that every PR also contains a `Fixes #XXX` commit message [1] with something like a new `fixes_issue` requirement. If `true`, a PR would not be automatically rejected if atleast one commit contains atleast one `Fixes #XXX`.

Ideally, pullapprove would also provide a way a way to perform an arbitrary check on the commit message(s) although that would be more complex (how would it interact with `fixes_issue`? Would it / could it apply to all the new commits on a PR, *etc*).

----
[1] - https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by davegaeddert** [comment]
Thanks for the detail here. We've been thinking the same and also about more arbitrary checks on commits messages, PR body, etc. I'm hoping we'll be able to get that sorted out relatively soon, but we've got a lot of stuff up in the air at the moment.

**Comment by jodh-intel** [comment]
Thanks @davegaeddert - understood. As as stop-gap, we've come up with a tool that checks the git commits directly for things like `Fixes #XXX`, line length, subsystem in subject line, etc. The plan is to have this called by our CI scripts:

- https://github.com/clearcontainers/tests/tree/master/cmd/checkcommits

It's not ideal as it's "further down the pipeline", but it gives us some of the features we'd really like to do at the pullapprove stage.

**Comment by davegaeddert** [comment]
The new PullApprove v3 is completely re-focused around the "human" aspect of code review, but allows you to integrate with other status checks if you'd like (ex. so review doesn't start until those other checks have passed).

So I think having these static checks/tests as separate tools is probably the right way to go! This also allows you to integrate your review workflow with other services like CI, codeclimate, or anything else that reports a commit status (https://probot.github.io/apps/).

More info about the new PullApprove can be found here: https://www.pullapprove.com
