### ISSUE TITLE
Small browser window obscures menu

### ISSUE THREAD

**Issue by tripleee** [pullapprove/support#113]
The "vertical ellipsis" menu in the upper right corner isn't visible in my Chrome window unless I scroll horizontally or maximize the window.

This means that the menu is hard to discover and rather impossible to use if you are not running your browser maximized.

Being able to view multiple windows at the same time is a common requirement among developers.  You should not get away with requiring the browser to run maximized at all times.

**Comment by tripleee** [comment]
Screen shot of my 2032x1606 Chrome window (with GUI decorations included in the dimensions).
<img width="1016" alt="screen shot 2017-07-03 at 9 13 21" src="https://user-images.githubusercontent.com/2160915/27780160-0d6da38c-5fd0-11e7-994f-74c0da413eb3.png">
Notice also how the wide dark slab on the left occupies screen space which could usefully have been populated with the stuff I can't see.

**Comment by tripleee** [comment]
Moreover, the chat icon in the lower right corner behaves like you would hope for the menu to also behave -- it floats where it's visible even when the window is smaller than the designer had hoped.

**Comment by davegaeddert** [comment]
Appreciate the feedback here (sorry we never responded). We're focusing on the new PullApprove v3 which is completely redesigned and rebuilt, and aren't planning to fix some of these things on the older version at this point. More info about the new version can be found here: https://www.pullapprove.com
