### ISSUE TITLE
Possibility to auto assign PR to reviewers

### ISSUE THREAD

**Issue by siempredelao** [pullapprove/support#114]
The idea behind this issue is that we want to always enforce two of any of our devs (by defining a users list or a group) to review a PR. Could it be possible to do this with PullApprove?

**Comment by davegaeddert** [comment]
Hi @siempredelao, can you say a little more about what you mean? Do you mean actually picking two specific users from a group randomly each time? Or assigning the actual "GitHub Reviewers" on the PR? Something else?

**Comment by siempredelao** [comment]
Hi Dave! I mean picking two random users from a group each time, being non consecutive for future PRs.

For example, if I have a group with users (A, B, C, D, E, F), first time I create a PR, B and F users are randomly auto assigned to the PR. Next time I create another PR, B and F cannot be selected for review, so for example, C and E get randomly assigned for review. Then, A and D and so on. 

_Sent from my HUAWEI VTR-L09 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by davegaeddert** [comment]
Sounds good @siempredelao. We had plans for a little while to implement a "round robin" kind of thing. I'll make sure we keep this in mind.

**Comment by davegaeddert** [comment]
The new PullApprove v3 has two options for selecting reviewers -- either randomly or in a specific order provided by you. We may be adding more options to that in the future, but "random" should at least get at the root of this problem.

More info here: https://www.pullapprove.com
