### ISSUE TITLE
Add conditions for signed-off-by requirement

### ISSUE THREAD

**Issue by mueller-ma** [pullapprove/support#115]
Hey,

we at https://github.com/openhab/openhab-android have crowdin setup to push translations to a specific branch and to create a PR to master branch. Is it possible to not require signed-off-by for those PRs? Example: https://github.com/openhab/openhab-android/pull/605

**Comment by davegaeddert** [comment]
Good question. We're probably not going to introduce all kinds of options for signed-off-by into the current version of pullapprove, but we are planning to rework a lot of this in the next major update (which I *really* hope we can get to soon). 

You might take a look at https://github.com/probot/dco for the signed-off-by aspect. There's a lot of discussions about these kinds of questions, but at least at a glance, it doesn't look like they've taken it much further than we have.

Let me know if you've got any other feedback/suggestions. We're working on a "master plan" for pullapprove and a lot of these kinds of comments help us prioritize what we plan to focus on. Thanks!

**Comment by davegaeddert** [comment]
We just put up the open preview for PullApprove v3, which supports integrating with other status checks for things like this. So going forward we'd recommend using something like https://github.com/probot/dco for specific checks/tests like this (which aren't necessarily related to the human aspect of code review).

More info here: https://www.pullapprove.com
