### ISSUE TITLE
File condition for root of the repo

### ISSUE THREAD

**Issue by nikoargo** [pullapprove/support#119]
We have a bunch of folders, each of which has a group which owns it. Perfect. But, we also have files in the root of the repo (like our `.pullapprove.yml`!) which we want to protect. Is there a way to specify files in the root of the repo without listing them all out manually and updating the `.pullapprove.yml` each time we add one? Maybe some sort of catchall reviewer that triggers only if no other file review has been triggered? Maybe we could use glob instead of fnmatch?

**Comment by davegaeddert** [comment]
Hey @nikoargo, can you show an example of how you'd set up your config if you could use glob instead of fnmatch? We're planning a bit of an overhaul that we're hoping to do at some point -- if the current file matching isn't flexible enough then we'll want to fix it! Thanks

**Comment by davegaeddert** [comment]
The new PullApprove v3 is more flexible here -- you can use fnmatch, or a regular expression to match file names/paths. I think you should be able to achieve this with a regular expression? We can look at adding glob that still has benefits.

More info here: https://www.pullapprove.com/docs/config/conditions/
