### ISSUE TITLE
Gamification of code review process

### ISSUE THREAD

**Issue by vaidik** [pullapprove/support#12]
I suggest that there should be a way to gamify code reviews so that doing proper code reviews can be improved over time. This is actually a problem a lot of engineers suffer through - they want to write code but they don't want to test it properly and they don't want to do code reviews as well. While they may not be bad engineers necessarily, they are good resources and they just lack the culture and practice of doing reviews. So why not push them in a direction that they are more inclined to do code reviews.

The kind of gamification I am suggesting is around code reviews. For example, a repo requires at least 2 reviewers. Whoever reviews gets some points for doing the code review. If the code review suggested changes, the developer goes back, makes the changes and pushes new commits. When new commits are pushed, ideally another round of code review is required to seek final approvals. So more or at least the same people review the code and get points for this round of review again. This also sort of syncs up with your plan to add a feature of resetting approvals when new commits are pushed.

**Comment by davegaeddert** [comment]
Thanks for putting this in here @vaidik -- if anybody else has comments or ideas for this, leave a comment!

**Comment by jaymecd** [comment]
That would be awesome, as I also think how to encourage developers to review more often and more accurate to leverage code quality.
👍

**Comment by davegaeddert** [comment]
Going to close this for now. We thought about trying to take this on with the new v3, but decided not to until we have a better idea of how it would work and that it actually _would_ work.

Happy to hear other ideas!
