### ISSUE TITLE
Disable review requests through Github API

### ISSUE THREAD

**Issue by Jean85** [pullapprove/support#120]
I wanted to avoid sending personal review requests through GitHub. I'm using a GitHub-group-based config, so I just want to require at least a single review from the matching group, and that's all, no single request.

That doesn't seem feasible under v3, because if I set `request: 0` on a group, the whole group is disabled. Is there any workaround for that? I had to revert to v2 for now.

**Comment by davegaeddert** [comment]
Hey @Jean85. I think you just need to set `required: 1` in addition to `request: 0`. By default, required is set to the same number as request if not specified (so they would both be 0 if you set `request: 0` only). Let me know if that does it.

**Comment by Jean85** [comment]
I was already using `required: 1` so no, that doesn't work unfortunately :disappointed:.

You can see it in https://github.com/php-fig/fig-standards/pull/1115:

![image](https://user-images.githubusercontent.com/6729988/48546168-f026a300-e8c7-11e8-960d-81643423c36b.png)

**Comment by davegaeddert** [comment]
If you click that "show inactive groups" checkbox, it will show you all the groups and their conditions. The status is saying that none of the groups met their conditions.

Maybe the confusion is in this one somewhere? How do you expect these conditions to work?
![image](https://user-images.githubusercontent.com/649496/48562535-00368680-e8b8-11e8-9f52-f71afadeb667.png)

Every condition must be true in order for the group to be activated (https://www.pullapprove.com/docs/config/conditions/). If you need to OR something, you just have to combine it into one statement right now (ex. `'New PSR' in labels or 'proposed/psr-8*' in files`).

**Comment by Jean85** [comment]
Oooh I missed that! Thanks for pointing that out, I'll try again ASAP.

**Comment by Jean85** [comment]
Tested and it works, thanks!
