### ISSUE TITLE
Cannot reenable PA for renamed GH repo

### ISSUE THREAD

**Issue by nik-kor** [pullapprove/support#121]
Hi!

Recently we renamed one of our organization's repos (it's private - sorry cannot share the link to it here). It wasn't automatically updated in PA db(?) and trying to enabling it again via UI here https://pullapprove.com/choose-repo/ leads to 500.

I guess, it rarely happens but can be useful for other ppl.

**Comment by davegaeddert** [comment]
Sorry I didn't respond to this earlier! I'm going to close it since we're focused on version 3 and I'm not aware of this happening very often.
