### ISSUE TITLE
Add support for child teams

### ISSUE THREAD

**Issue by jmeijrink** [pullapprove/support#122]
Please add support for the Github feature of nested teams (defining a parent team on another team). We currently get the message that the child teams cannot be found. 

I don't think we should consider this functionality preview, as it is already available for 1.5 years.

**Comment by davegaeddert** [comment]
Hey @jmeijrink,

I think I might have just responded to one of your coworkers (?) but I can share what I said here too.

I've opened a support ticket with GitHub to confirm this, but right now I think the only way to make this work is to directly invite the nested team to your repo. We currently use the repo teams list endpoint to see which teams are available (https://developer.github.com/v3/repos/#list-teams) and it doesn't seem to list nested teams even if we use the API preview for nested teams.

I know that's a bit of a pain to invite those nested teams (and defeats the purpose of nesting in some ways) but I think that's the best solution while we get this sorted out. I'll leave this issue open -- thanks!

**Comment by jmeijrink** [comment]
Ok, Dave. Clear, thanks for going after it.

-Jorre

**Comment by davegaeddert** [comment]
This has (finally) been resolved!
