### ISSUE TITLE
Recieving Billing error: Billing account is not set up

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#124]
When attempting to test in the `angular/angular` repo, I am seeing `Billing error: Billing account is not set up`

The failure can be seen [here](https://app.pullapprove.com/report/?url=https%3A//storage.googleapis.com/pullapprove-storage/reports/4022fc90-e612-4e9d-83b0-25cb94f3ea99.json%3FExpires%3D1577118969%26GoogleAccessId%3Dpullapprove-reporter%2540pullapprove.iam.gserviceaccount.com%26Signature%3DotWK25u5p%252BK2KDK950h9ENdu9qVWkw4Ff2isjguGvEtc24dz0qfYsg9GM%252BwzpWeHUv%252FT%252FUWplRZWju9znvmEg%252BiEfdNH4fCnn%252FvG0wuVp0WAc%252FkTMcGbEGNh4UzVzbLOhFPaSarMH%252FaAW7RnZjDp0kt56he93zSx3YhEe1Z5gs9iSQlh0bzoG81uq7YdPD1CbY7%252F9ntU1f3JHSYgPtichJqrDx3eY2PgAB%252FuB8%252F9Qj5ZYzuDFWaGQuTbLajS%252F8cosW4FKSsc65wlkGdau0y4%252B%252BDySaaOx2FhurUc5XLWPIdunWq5uyBuYvWuZchm7Ut5ba7CDSVBbi1nh26xU9ljRQ%253D%253D&fingerprint=e41f215031f2c16830dc613115edce75) for [this PR](https://github.com/angular/angular/pull/33374)

**Comment by davegaeddert** [comment]
Looks like the "angular" org already trialed pullapprove back in April, so you'll need to choose a plan at app.pullapprove.com.

Let me know if you have any trouble with it -- maybe email me instead if there are specific billing related questions.
