### ISSUE TITLE
Prevent PR author from being assigned as a reviewer

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#125]
In our configuration we use:
- `author_value: 0`
- `request_order: random`

If the author of a PR is one of the users in the group, we would like them to be prevented from being assigned by PullApprove.

For example in https://github.com/angular/angular/pull/32241, I am the author, but I am also the [reviewer assigned according to PullApprove](https://app.pullapprove.com/report/?url=https%3A//storage.googleapis.com/pullapprove-storage/reports/0ac6eed1-06fe-4c9d-9df6-e6b7f398108b.json%3FExpires%3D1585420297%26GoogleAccessId%3Dpullapprove-reporter%2540pullapprove.iam.gserviceaccount.com%26Signature%3DGtKCiCLdx2n%252FZmnUD%252FdwdXCLUedbQbaZQ386RZZpTI2o%252FdOmVWOm4zUNSJMkgJV4FoHMf5yz440ObgBMAx5A8Dma5x%252F0V3vXSbBjMOCnM9bHzMxromnzmPNkd0fq5MjSk5rJGGucdUng0k0HeXYv9ww3XWkvACPqPD97HPyetRcbjxG3qWZ35L8%252FHzRrPYYyFiuk5eKorFHObBe8rs8Z23nNqINs8uk1zrymTTGQgvkdIle7w4YArkmSILeJ5vj1Sh%252FwxlpWAIgZp4UFrm25PGiWfpqkp3SceYa4h3phoe3YkzSsYe5FDTMaN9JQb0k22KjFzjlKX83SYbyuX7l%252FsA%253D%253D&fingerprint=ad110284e46cd307bed0b1e323951ee2).

It is a little confusing because, looking at Github there is no user requested as a reviewer at all. 
additionally, I am unable to provide the review on Github, so this PR is in a terminal state and would likely fall through the cracks.

Since we don't allow authors to approve their own PRs it does not make sense that an author can be assigned to review their own PR.  We still want to use the `author_value: 0`, however the PR author shouldn't cause more reviews to be necessary.

**Comment by davegaeddert** [comment]
Thanks @josephperrott -- this was a bug! The author can't approve their own PR in GitHub or be a requested reviewer. There is a scenario where we mark people who have left "comment" reviews as "pending", to indicate that they have looked at the PR and are now involved, but didn't approve or reject it. So it was considering you as "pending" because of your test comments -- that's been fixed now and it should change you to "unavailable" if you run it again because you're the author.

**Comment by josephperrott** [comment]
It looks like this happened outside of the scenario you outlined.

If you look at https://github.com/angular/angular/pull/35043, PullApprove identified needing reviews from `docs-infra` and `size-tracking` as you can see [here](https://app.pullapprove.com/report/?url=https%3A//storage.googleapis.com/pullapprove-storage/reports/c39ea433-5dca-4889-8677-216140befa83.json%3FExpires%3D1585516515%26GoogleAccessId%3Dpullapprove-reporter%2540pullapprove.iam.gserviceaccount.com%26Signature%3DjU1Yq1fcbGGypB7YeuDTYYMtTZbsJD273xgbTJrbxp7zoBRJG43%252FBLWr8nekt9lTg3OqZKY4RGJEl5oEtruzlB%252FQxfmsgv4p7Vh9FybeZ0dEyZR1%252BYh%252Boo3n5tw6r9qOuCSD087rKCZlrcejKWZPGZ9IlZ%252FFeCVO30aXXsBRZ1xpjg7I1ITkN%252F%252BtG3nG09KsPs4Cj%252F4LE%252FdoNVA%252BljUZQl85kYgEERSR%252FrArrjPDT6oDnv3bAYYJVkJGITuzVdEr5cXH4i5PwsUXKNaiPcCqXDlsIhL8JmoU43rN6%252BVjs3tnuzjRuH4zGR5Yh4VMjIm5rFLhy4SeSLUNhojv3KLk5A%253D%253D&fingerprint=2e5e2c742633719755fac1455aa3884a).

However the `size-tracking` group was not requested, presumably because the author was in the user list.  


Alternatively it could be an issue of the fact that all of the users for the group are in our global approvers group.

```
size-tracking:
    conditions:
      - > ... <removed for space>
    reviewers:
      users:
        - IgorMinar
        - kara
      teams:
        - ~framework-global-approvers
```

`framework-global-approvers` group membership is :
```
- IgorMinar
- josephperrott
- kara
- mhevery
```

You can see in the [pullapprove link](https://app.pullapprove.com/report/?url=https%3A//storage.googleapis.com/pullapprove-storage/reports/c39ea433-5dca-4889-8677-216140befa83.json%3FExpires%3D1585516515%26GoogleAccessId%3Dpullapprove-reporter%2540pullapprove.iam.gserviceaccount.com%26Signature%3DjU1Yq1fcbGGypB7YeuDTYYMtTZbsJD273xgbTJrbxp7zoBRJG43%252FBLWr8nekt9lTg3OqZKY4RGJEl5oEtruzlB%252FQxfmsgv4p7Vh9FybeZ0dEyZR1%252BYh%252Boo3n5tw6r9qOuCSD087rKCZlrcejKWZPGZ9IlZ%252FFeCVO30aXXsBRZ1xpjg7I1ITkN%252F%252BtG3nG09KsPs4Cj%252F4LE%252FdoNVA%252BljUZQl85kYgEERSR%252FrArrjPDT6oDnv3bAYYJVkJGITuzVdEr5cXH4i5PwsUXKNaiPcCqXDlsIhL8JmoU43rN6%252BVjs3tnuzjRuH4zGR5Yh4VMjIm5rFLhy4SeSLUNhojv3KLk5A%253D%253D&fingerprint=2e5e2c742633719755fac1455aa3884a), the group is correctly expanded, however they are all marked as unavailable.

**Comment by davegaeddert** [comment]
Yeah I think all that's happening here is that everyone in framework-global-approvers is being marked as unavailable because of the [`~` prefix](https://github.com/pullapprove/support/issues/123#issuecomment-545238585). That's an interesting scenario that I don't think had been considered though... I'll have to look at it to see what's feasible, but would you have expected IgorMinar and kara to be eligible for a review request (and really just kara because IgorMinar was the author in this case)?

**Comment by josephperrott** [comment]
Yes, the expectation would be that it would be either IgorMinar or kara, and as you noted Igor was the author so in this case specifically it would have to be Kara.

**Comment by davegaeddert** [comment]
@josephperrott this should work as expected now. Let me know if you have other questions about it.
