### ISSUE TITLE
Documentation unclear with regards to available request_order options

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#126]
Based on the documentation it appears that two valid `request_order` values are `given` and `shuffle`, but if no value is provided in the config it appears that `random` is the value assigned based on the debug provided.

Is it possible to document/list all of the available orders and how they work at a high level?

**Comment by davegaeddert** [comment]
Yeah, the existence of both `random` and `shuffle` is an unfortunate side-effect of history, but they're the same thing.

Hopefully this helps clarify some things? https://docs.pullapprove.com/config/reviews/#request_order

I'll try to give some more attention to the docs this week... they are in need!
