### ISSUE TITLE
PullApprove requests a review for an already closed PR

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#127]
See this PR: https://github.com/angular/angular/pull/34545

PullApprove requested a review on a PR that has been closed for 30 days, it seems odd that it would create in this review request, since the PR is closed.

**Comment by davegaeddert** [comment]
Interesting. It must have been the lock event for the PR that triggered it to run? I'll have to see if there's a good place I can insert a check to prevent this kind of thing...

**Comment by davegaeddert** [comment]
Decided to disable all modifications to review requests if the PR is closed.
