### ISSUE TITLE
Add checklists as criterion for merging

### ISSUE THREAD

**Issue by SaurabhJha** [pullapprove/support#13]
I suggest that we include checklists as part of code review process.

A lot of pull requests have an associated list of things to be done before it is fit for merging and they are often added as a TODO checklist on description of the PR. For example, adding a database table might be necessary before some piece of code can go into master.

The idea is to not allow a Pull request to be merged unless all the items have been checked.

cc: @vaidik

**Comment by davegaeddert** [comment]
Thanks @SaurabhJha, I love this idea and we'd definitely use it internally. I haven't looked into it much yet, but it doesn't look like there's an official GitHub API for this but I think it'd be a pretty easy thing to do ourselves.

**Comment by davegaeddert** [comment]
The new PullApprove v3 is refocused on the human aspect of code review, and we suggest that specific tests/checks like this be implemented separately. There may even be a probot (https://probot.github.io/) app that does this already?

I'm going to close this for now. More info about PullApprove v3 can be found here: https://www.pullapprove.com
