### ISSUE TITLE
Rule unexpectedly fails glob matching of changed file in PR

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#131]
For https://github.com/angular/angular/pull/36204 it looks like our file failed to match the expected rule as shown [here](https://app.pullapprove.com/report/?url=https%3A//storage.googleapis.com/pullapprove-storage/reports/7faac257-e66e-4bd5-b136-d8b60b7e5f6c.json%3FExpires%3D1590172819%26GoogleAccessId%3Dpullapprove-reporter%2540pullapprove.iam.gserviceaccount.com%26Signature%3DhxinWn8OfFGx8SXQo1p8cPtYVCqgSRxVZa%252Fw4PxXcNjTf1AhrQB1mWgwAysqB2FfxQVk0omYzUycX%252FG4INe9mF3lE7fwZPnNi4dNkGOjnjfY0jgnA%252B8CVFEwaMMH3ivaWo0vv9xW3Pb3kAtqGOc%252Bk8FvCwMMC63hrnRfMy8LTHQ%252Bv4CFUCGGF%252Boc1CgCkZmHwqF8kAQy3oRORUoBx2LHUBZjiLR2%252B9c62AvO%252BzNfereiwzcNUzrERzXRJIt7e8jcrNij6d9qnf8y0TCYy1DvciZe5yODZ3WEIAcVBGsDWYtlErJ7SH601C%252BTKwAhTMSq7Sy1SVVFpXWHcPKnYnXJwg%253D%253D&fingerprint=1766fd5572c360cc4c0aef659109094d).

The only file changed in the PR is:
```
- tools/gulp-tasks/format.js
```

And I would expect that this group have matched
```yaml
# =========================================================
#  Dev-infra
# =========================================================
dev-infra:
  conditions:
    - >
      contains_any_globs(files, [
        '*',
        '.circleci/**',
        '.devcontainer/**',
        '.github/**',
        '.vscode/**',
        '.yarn/**',
        'dev-infra/**',
        'docs/BAZEL.md',
        'docs/CARETAKER.md',
        'docs/COMMITTER.md',
        'docs/DEBUG.md',
        'docs/DEBUG_COMPONENTS_REPO_IVY.md',
        'docs/DEVELOPER.md',
        'docs/GITHUB_PROCESS.md',
        'docs/PR_REVIEW.md',
        'docs/SAVED_REPLIES.md',
        'docs/TOOLS.md',
        'docs/TRIAGE_AND_LABELS.md',
        'goldens/*',
        'modules/e2e_util/e2e_util.ts',
        'modules/e2e_util/perf_util.ts',
        'modules/*',
        'packages/*',
        'packages/examples/test-utils/**',
        'packages/private/**',
        'packages/examples/*',
        'scripts/**',
        'third_party/**',
        'tools/brotli-cli/**',
        'tools/browsers/**',
        'tools/build/**',
        'tools/circular_dependency_test/**',
        'tools/contributing-stats/**',
        'tools/components/**'
        'tools/gulp-tasks/**',
        'tools/ng_rollup_bundle/**',
        'tools/ngcontainer/**',
        'tools/npm/**',
        'tools/npm_integration_test/**',
        'tools/pullapprove/**',
        'tools/rxjs/**',
        'tools/saucelabs/**',
        'tools/size-tracking/**',
        'tools/source-map-test/**',
        'tools/symbol-extractor/**',
        'tools/testing/**',
        'tools/ts-api-guardian/**',
        'tools/tslint/**',
        'tools/utils/**',
        'tools/validate-commit-message/**',
        'tools/yarn/**',
        'tools/*',
        '**/*.bzl',
        '**/*.bazel'
        ])
  reviewers:
    users:
      - devversion
      - filipesilva
      - gkalpak
      - IgorMinar
      - josephperrott
    teams:
      - ~framework-global-approvers
```

However, in the PullApprove result linked above it is shown to fail this condition.

**Comment by davegaeddert** [comment]
This took a few minutes to realize... but there's a comma missing on the line before gulp-tasks. So it's treating that like a multi-line string and the pattern is then `tools/components/**tools/gulp-tasks/**`. I'm not sure what pullapprove could have done to help catch that? Let me know if you have ideas.
