### ISSUE TITLE
Received "error - Internal error" from pullapprove

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#132]
We recieved [this](https://app.pullapprove.com/report/?url=https%3A//storage.googleapis.com/pullapprove-storage/reports/c50d2e3b-9e63-469b-bd42-4208b6a95f95.json%3FExpires%3D1590915857%26GoogleAccessId%3Dpullapprove-reporter%2540pullapprove.iam.gserviceaccount.com%26Signature%3DoQ0rVyTOKzhBFTc83V1DNCwjIfXemKwDgUGeT5jarUJELRaRWrw30lLDsAQB9yVi6sDHEHuFYokWOLkd1vDH86bFaXw9b9fr4qiC8hgVCvJOXNhJFbc5txiBKGXmXeYfvhwHDAVA4xhcYXOvqnOnWEualGAE7EjSpsuJmQjNcFjZ%252FX0QlJ6B4rd9RWD8NNEn4Rdj6qG%252FlNvuWwmDj4yjnpK28NFDL8P77yN2uX7JhW%252F8YzoRuCrZjTFtqaoKdYqCV%252FUem6SBOBs3afLMJY%252FEQZed7vX4c5NpSA9KDeLOwhxLQmFUxoPEiaWAk3Y6BCLjv6WXTbzMbe%252Bd6nk4qH0YTQ%253D%253D&fingerprint=24f29ad907bb8489ef9557fd6d72d154) error on https://github.com/angular/angular/pull/36362

Is it possible to find out more information about the failure, or trigger a rerun from the failure UI?

**Comment by davegaeddert** [comment]
Any error that shows up like that is basically "unhandled" at this point and they are essentially down to periodic GitHub (or Google/AWS) API errors. I can look again at how we might handle those differently now that we have quite a bit of data on them (messaging, retries, etc.), but that's the story. 

In terms of rerunning them, the solution at the moment is for the PR to trigger another pullapprove-relevant event. The simplest thing I usually tell people is to add/remove a label on the PR. Typically though, for these intermittent kinds of API/network errors, another event will happen naturally on the PR (commit, review, label event or a number of others) and it will resolve itself pretty quickly.

This is clearly an area that needs a little bit more attention at the moment, but that's where it stands right now. Thanks for raising it as a need and keeping it on the radar!

**Comment by josephperrott** [comment]
We are seeing this `error - Internal error` message again [here](https://app.pullapprove.com/report/?url=https%3A//pullapprove-storage-production.s3.amazonaws.com/reports/af49369b-3311-441f-ac16-8309ffcf5ac3.json&fingerprint=c39099bf002f7577ac6bec1314e0eff7) on https://github.com/angular/angular/pull/36517.

Even attempting to retry it later with another pullapprove-relevant event resulted in the same error.  Is it possible for you to confirm that this should be a transient error?

**Comment by davegaeddert** [comment]
Hmmm... so there is an uncaught API error but I'm not sure what the way to fix it is. Somehow GitHub allowed IgorMinar to be requested twice, which I think is the root of the issue:
![image](https://user-images.githubusercontent.com/649496/88821161-f0440080-d187-11ea-8715-efdb00032991.png)

PullApprove is trying to remove IgorMinar, but getting an "Unprocessable Entity for url" error.
```sh
# call
GitHubAPI.response status=422 url=https://api.github.com/repos/angular/angular/pulls/36517/requested_reviewers args=() kwargs={'json': {'reviewers': ['IgorMinar']}} method=delete
# error
422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/angular/angular/pulls/36517/requested_reviewers

{"message":"Validation Failed","errors":["Could not add requested reviewers to pull request."],"documentation_url":"https://developer.github.com/v3/pulls/review_requests/#delete-a-review-request"}
```

Do you have the ability/permission to try quickly removing one of the Igors from the requested reviewers in the GitHub UI and see if it can be cleared up?

**Comment by josephperrott** [comment]
I also get `422 Unprocessable Entity` when I attempt via the API and attempting via the UI just has no effect.

**Comment by davegaeddert** [comment]
Ok. I've seen this before but it's been a long time. Seems like a legit GitHub bug to me though. Come to think of it, I'm pretty sure I've had a conversation with them about it before and thought they said it was fixed...

Happy to open a ticket with them if you'd like me to. Might make more sense for you to do though as a part of the angular organization/repo?

Not sure what to say on the specific PR. Unless they can fix it on the backend, the easiest thing to do is probably use admin permissions to merge regardless of the checks and see if it ever happens again (I assume this is the first time for you)?

Let me know what you think.
