### ISSUE TITLE
Unable to trigger config test with /pullapprove-test

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#135]
It seems that I am unable to trigger a test of a config using the `/pullapprove-test` command.

I am unsure what I am doing incorrectly as I have been able to do this in the past.  You can see my attempts on this PR: https://github.com/angular/angular/pull/36915

**Comment by davegaeddert** [comment]
Thanks for the issue -- I was looking at the error this morning and hadn't yet found the bug. Looks like you have some keys that are ints, and it's causing a JSON dump error (can't compare ints to strings when sorting): 
![image](https://user-images.githubusercontent.com/649496/84192930-518d0480-aa60-11ea-837b-f1951ab79b4e.png)

I'll see if there's something I can do on my end, but the quick fix will be to make those strings.

**Comment by josephperrott** [comment]
I can definitely change it on our end, I just didn't have great names so I just started numbering things.  Thanks for sorting it out!

**Comment by josephperrott** [comment]
I can confirm that it works as expected after changing out the keys to be strings.
