### ISSUE TITLE
Config matching failed to match our fw-service-worker group as expected

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#137]
In a PR found at https://github.com/angular/angular/pull/37555, our pullapprove config failed to match as expected.

The pullapprove report can be seen [here](https://app.pullapprove.com/report/?url=https%3A//storage.googleapis.com/pullapprove-storage/reports/1d6e832b-f69f-4a5a-a8a4-090c9a42ed2a.json%3FExpires%3D1597219185%26GoogleAccessId%3Dpullapprove-reporter%2540pullapprove.iam.gserviceaccount.com%26Signature%3DWbiPGn66nMmCi5Ftvbwj45cGAvSNJ%252FdS4RxpeUmFcpwf8%252B3o5I8ZUK3K8Gmf96gnF4YGNrOx%252F2NUPV%252BjYHmh5ZkKVah5fTxpC7weQnowLEaWZGrHfxCVInP%252F%252FaVEw1CuIqdQPGOLgBGL9MoqorgEv%252FOTBhMbOtNlmfqbNLKLZSj%252B9dkbwg8UERiCAtmCkDRYtWUdndDS7lRQDG3ouaKgRZloobxKSBjJXOY4J26vdGb5LRZi3NnqvWc6Fo2RPOoFFP1XSFvFVVipmoDhOw2No2xCfqCW0iV2nNpbZKvoZXBoomPHPss7zCepTvAWriX%252BPl%252BcGNeczYF7G3%252BVeCAB%252BQ%253D%253D&fingerprint=ad8adc9c1b2ad5d2e0a1066e6240b724)

The changed files for the PR can be found [here](https://api.github.com/repos/angular/angular/pulls/37555/files)

It is expected that it would match our `fw-service-worker` group as defined [here](https://github.com/angular/angular/blob/master/.pullapprove.yml#L543)

**Comment by davegaeddert** [comment]
Check me here, but it just looks like the fw-service-worker group was no longer required because global-docs-approvers approved the PR. Looks like the files condition was a match:
![image](https://user-images.githubusercontent.com/649496/84821985-99bca180-afe1-11ea-8a91-56b33cd8b43e.png)

Admittedly the terminology is getting a little confusing for this kind of set up, but I think it's doing what you asked it to do?

**Comment by josephperrott** [comment]
Ahh I see I was misunderstanding, or rather didn't think through how the `"global-approvers" not in groups.approved` would effect the other groups.  

I will need to rethink how we identify when out `fallback` group is matched.

Thanks!

**Comment by davegaeddert** [comment]
Sounds good. Let me know how it goes.
