### ISSUE TITLE
Unclear pattern syntax for `Groups` in conditions context

### ISSUE THREAD

**Issue by devversion** [pullapprove/support#141]
Hello! I see that `groups` exist in conditions through the context. The `Groups` struct seems to provide methods for `include` and `exclude`, but the docs seem to refer to `files` in the example. Is that intended?

It might be better having concrete group examples here, and potentially even expanding whether actual file patterns / globs are supported here. i.e. if usual semantics of single or double asterisks apply here.

https://docs.pullapprove.com/context/#group

![image](https://user-images.githubusercontent.com/4987015/88209494-167f1300-cc53-11ea-9e87-8944aee98eb3.png)

**Comment by davegaeddert** [comment]
Good point @devversion! The docs really need some help right now. I think some of this detail actually used to be included but was somehow lost... The `include` and `exclude` do work on groups despite the examples -- syntax is the same. By default it uses the simpler ["fnmatch" single-asterisk syntax](https://docs.python.org/3/library/fnmatch.html), but there are some other examples (again using files) here that show how to optionally use globs: https://docs.pullapprove.com/config/conditions/#files-and-paths

Let me know if that helps for now!
