### ISSUE TITLE
Bug: app.pullapprove.com/report landing page resize issue

### ISSUE THREAD

**Issue by jessicajaniuk** [pullapprove/support#145]
There's a bug with the report landing page that displays groups related to mouse movement. It appears that an event handler is firing related to either onMouseMove or onMouseLeave that adjusts the height of the iframe containing the reported groups improperly. It seems to set the height of the iframe to a top padding plus current mouse position rather than the full height of the content of the iframe itself. It makes it near impossible to actually see the groups assigned. My workaround is to literally view the source, grab the iframe src url and paste it into a new tab.

![resize-issue](https://user-images.githubusercontent.com/72768744/105099616-cc8bb400-5a60-11eb-9c61-f757c2951d36.gif)

**Comment by davegaeddert** [comment]
Well that's no good! I will take a look -- thanks for reporting it.

**Comment by davegaeddert** [comment]
Should be fixed now. Please let me know if you see otherwise.

**Comment by jessicajaniuk** [comment]
Looks great now! Thanks!
