### ISSUE TITLE
pullapprove not recognising travis passes

### ISSUE THREAD

**Issue by mshadbolt** [pullapprove/support#146]
We have a repo that should uses pullapprove and Travis CI, recently we have been encountering an issue where pullapprove is not recognising that the Travis check has succeeded. Can anyone help with this? We have tried to update the config file but nothing has seemed to work and we are a bit stuck. 

Our [previous configuration stated](https://github.com/HumanCellAtlas/metadata-schema/blob/ad69d084d5f55e6105497a32eaa3b98f16460193/.pullapprove.yml#L17):
```
- condition: "'*travis*' in statuses.successful"
  unmet_status: failure
  explanation: "Travis CI tests must pass before review starts"
```

When this wasn't working we tried [updating the configuration to](https://github.com/HumanCellAtlas/metadata-schema/blob/ff27788edc635f6e631a64b3fcda63f54fc6fe7b/.pullapprove.yml#L17):

```
- condition: "'*[tT]ravis*' in check_runs.success"
  unmet_status: failure
  explanation: "Travis CI tests must pass before review starts"
```

Here is an example pull request where we tried updating the configuration to get pullapprove to recognise that the travis build succeeded:

https://github.com/HumanCellAtlas/metadata-schema/pull/1341

It shows that even though the Travis Build succeeded, pullapprove has not recognised it.

Thanks in advance for any help!

(tagging @ESapenaVentura)

**Comment by davegaeddert** [comment]
Hey @mshadbolt -- it looks like you made the right call on switching to "check_runs". And I can see in your last /pullapprove-test that it does work:

![image](https://user-images.githubusercontent.com/649496/108933993-b948a700-7611-11eb-95d9-b4757b0df1b7.png)

I will check the logs for an API error or missed webhook or something, but I wonder if the pullapprove status just isn't up-to-date on that PR? Could you try adding/removing a label on that PR to trigger an update?

**Comment by mshadbolt** [comment]
hi, thanks for the reply.

I tried adding a label to re-trigger the checks, but it seems that it still doesn't recognise that travis has passed and it is stuck in a pending state, which I am not sure why or what it means

<img width="1232" alt="Screenshot 2021-02-24 at 13 36 00" src="https://user-images.githubusercontent.com/13007987/108946295-ae3f5680-76a5-11eb-8cf7-a2b36591c7df.png">

<img width="942" alt="Screenshot 2021-02-24 at 13 36 26" src="https://user-images.githubusercontent.com/13007987/108946327-c0b99000-76a5-11eb-9263-46f65ee49c73.png">

**Comment by mshadbolt** [comment]
oooh actually i just realised this 'pending' status means it is pending review by the reviewer that was requested so it is working now!! sorry, dumb moment, just getting back into using the tool, thanks a lot for your help.

**Comment by mshadbolt** [comment]
Actually now it has gone back to the previous status of saying Travis hasn't succeeded after I pushed another commit to the branch

<img width="934" alt="Screenshot 2021-02-24 at 13 52 26" src="https://user-images.githubusercontent.com/13007987/108947212-910b8780-76a7-11eb-9040-5d25345a9ec4.png">

**Comment by mshadbolt** [comment]
then when I remove the label I put on before, it goes back to the proper 'pending' status. This seems like quite strange behaviour...

**Comment by davegaeddert** [comment]
Strange indeed. I'm not seeing any check_run webhooks being sent to us for HumanCellAtlas, which would explain why it isn't updating itself when Travis passes.

Do you have permission to manage the pullapprove installation by chance? The `check_runs` is a relatively new feature and we had to update the app permissions in order to do it. Every time we change webhooks/permissions, each installation has to approve the change in access. GitHub sends an email when this happens but it could have been missed -- if the new permissions weren't ever approved then that might explain why we aren't seeing webhooks for check_runs.

If someone could look at the installation page, I think it will show an alert/prompt to grant the new permission if that hasn't happened yet:
https://github.com/organizations/HumanCellAtlas/settings/installations/571959

**Comment by mshadbolt** [comment]
ok great, thanks for looking into this further. I will follow up with the administrator of the organisational github and hopefully they can grant the correct permissions and it will all be fixed. Will let you know how I go.

**Comment by mshadbolt** [comment]
Hi, I asked my administrator to grant the permissions but it is still not recognising that travis passes until i add/remove a label which is kind of annoying...

**Comment by davegaeddert** [comment]
Hmm. From what I can see on my end, the app still doesn't have the access it needs. We should see "check_run" in the events and `"checks": "read"` in the permissions:

![image](https://user-images.githubusercontent.com/649496/109677195-0b705780-7b3f-11eb-8948-bf78dd1d7127.png)

Did the administrator say whether or not they actually changed anything? Any chance they could send a screenshot of the installation page where it shows "checks" in the permissions?

![image](https://user-images.githubusercontent.com/649496/109677834-a832f500-7b3f-11eb-8a4b-3cb6ffec3565.png)

Sorry to be a pain but I just can't see any of that stuff from your end. It's possible that there's some sort of GitHub bug going on here and we need to involve GitHub support, but it would be nice to confirm things are set up properly first if possible! Thanks.

**Comment by mshadbolt** [comment]
Hi thanks for checking again, no worries it is hard for me too because I can't see it either. I was told they changed it but perhaps there wasn't an understanding of exactly what to do.

@lauraclarke are you able to check the above again for the HumanCellAtlas/metadata-schema repo. thanks.

**Comment by lauraclarke** [comment]
Looks like there was another permissions request I didn't get notified about that I have now approved This is what it looks like in the system at the moment 
![Screenshot 2021-03-03 at 10 08 04](https://user-images.githubusercontent.com/8376192/109789633-6e79f100-7c08-11eb-99d5-54cf281631b1.png)

**Comment by davegaeddert** [comment]
Thanks @lauraclarke! I think that will probably clear up the issue. I'll close this for now, but @mshadbolt please let me know if you still have questions!
