### ISSUE TITLE
PullApprove extension no longer appearing in page

### ISSUE THREAD

**Issue by josephperrott** [pullapprove/support#147]
It appears the chrome extension no longer inserts into the page.  I suspect something may have change in the DOM for Github's UI, and your triggering node is no longer found.

**Comment by davegaeddert** [comment]
Submitted a new version which should be available soon. Thanks for the heads up (your suspicion was correct).

https://github.com/dropseed/pullapprove-browser-extension/releases/tag/v0.1.2
