### ISSUE TITLE
YAML templates

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#15]
Again, thanks @vaidik for brining this one up.

The idea is to have organization-wide .pullapprove.yml settings. This would make it much easier to make changes across multiple repos (ex. change your approval keywords across your organization) and also speed up the process of setting up a new repo. It was also mentioned that this would be useful on a GitHub Team basis.

> Also, going forward you might want to consider Github Team-level configuration as well. In a setup like ours, we have one team that has 5-6 repos under them. They might want to configure things slightly differently. A simple use-case is that our Data Analytics team in Bangalore might want to use LGTM for approving pull requests to their repository but our Consumer team in New Delhi may want to use +1 for their repos. According to the current setup, I see us doing this over and over in every repo. It would be nice if we can do this with multiple repos at the same time.

I think I'd like to generalize this into "templates" (or something to that effect), that aren't necessarily tied to GitHub Teams or anything else. You could obviously still use it that way, but it would be more flexible and could accommodate many more scenarios. The idea would be that you can create as many templates as you want, then when setting up a new repo (which still needs its own .pullapprove.yml) you start it with:

``` yaml
extends: data-analytics-team
# anything following would override the template
```

I'm not sure what the best term is -- `extends`, `overrides`, `use_template`, `template`, etc. The templates would probably have to live on pullapprove.com (or maybe in a special repo??).

**Comment by nimajalali** [comment]
+1

This would make managing hundreds of repos more feasible.

**Comment by bka9** [comment]
I would be in favor of adding the ability to assign entire github teams as approvers. It seems a little daunting to manage permissions in many different places.

**Comment by davegaeddert** [comment]
@bka9 good input, someone recently created an issue about that here: #25

**Comment by davegaeddert** [comment]
@vaidik, any interest in giving this a try? If you go to an org repo on pullapprove.com, just click the org name at the top.Then you should see a "Yaml Templates" heading with a "create" button next to it. No real documentation yet but let me know if you have questions! Then use `extends` in your repo .pullapprove.yml to use it.

**Comment by gabrieljoelc** [comment]
@davegaeddert we have been trying out the template with extends for about a week. We started having issues that seem related to getting a ping back from pullapprove. They are getting stuck in this state:
![image](https://cloud.githubusercontent.com/assets/147849/12760557/27f30c74-c9a4-11e5-84d6-26625067f380.png)
Not sure if it's related to templates or not but seemed to start after we starting using.

**Comment by davegaeddert** [comment]
Hey @gabrieljoelc, I don't think this is related to the YAML templates but I do have a couple ideas of what's going on. If you let me know which repo and PR number(s) you're getting this on, I'll take a look.

**Comment by davegaeddert** [comment]
@gabrieljoelc I think I figured out what this was -- I'm guessing you got this when you pushed new commits? And are not using the `reset_on_push` setting? Should be fixed now.

**Comment by gabrieljoelc** [comment]
Probably, yes. Definitely, yes, we are not using `reset_on_push` setting.

Yes, I believe it's fixed! Thanks

**Comment by davegaeddert** [comment]
Ok, these could use a little more UI/UX on pullapprove.com but the initial documentation has been started here:
http://docs.pullapprove.com/yaml-templates/
http://docs.pullapprove.com/yaml/extends/

Thanks everyone!
