### ISSUE TITLE
"At least N other collaborators" mode?

### ISSUE THREAD

**Issue by jackfirth** [pullapprove/support#16]
When using PullApprove with a simple project consisting of maybe one or two main collaborators and the occasional side developer, I find myself wishing I could get rid of the notion of "these people are PR reviewers" and replace it with "as long as at least 1/2/N other people with access to the repo approve it, you're good". Then I don't have to configure who has approval or worry about self approval, or update the list of reviewers when a new collaborator joins. This also would make setting up new repos much simpler.

**Comment by davegaeddert** [comment]
Thanks @jackfirth!

So it feels like the most obvious piece of this is to allow people to choose a more dynamic setting for the `members` part of a reviewer group, probably by adding an `all` option:

``` yaml
reviewers:
    required: 4
    members: all
```

Not sure I'd want to go this far right away, but I could also see a point where it would be nice to segregate collaborators based on GitHub Teams (`members: testers`, etc.) and/or GitHub permissions (`members: read`, `write`, `admin`).
![image](https://cloud.githubusercontent.com/assets/649496/12069828/98c0a52c-b015-11e5-9e6e-faee0dd3a899.png)

As far as the "1/2/N other people" part, my first thought was to keep the `required` field as a number, and just use numbers between 0 and 1 to get at what you're looking for:

``` yaml
author_approval: ignored
reviewers:
    required: 0.5  # half
    members: all
```

Not sure if that's the best way to do it, but it would avoid a lot of math interpretation / evaluation and I think still have the same effect?

**Comment by jackfirth** [comment]
Using the members setting seems like a great way to do this. A ratio would probably just be confusing, since in my experience code review policies tend to look like "get any two people to sign off" regardless of team size rather than "get a quarter of the team to sign off". Also if people join or leave the project while a PR is still open, what happens? Any resolution to that would be unintuitive behavior to me.

**Comment by davegaeddert** [comment]
Agreed, I think I misinterpreted your comment -- I thought you meant a ratio when you said "1/2/N", now I'm assuming you meant "1 or 2 or N". So would adding an "all" option to members basically give you all the functionality you're looking for at the moment?

``` yaml
reviewers:
  required: 2
  members: all
```

**Comment by jackfirth** [comment]
Yup, that's exactly what I'm looking for (when combined with the setting to disable self-approval)

**Comment by davegaeddert** [comment]
@jackfirth I took a stab at this. Do you want to give it a try?

**Comment by davegaeddert** [comment]
Added initial documentation here: http://docs.pullapprove.com/yaml/reviewers/

This has been out in the wild for a while, so I'll close this issue.
