### ISSUE TITLE
Handling multiple regex examples

### ISSUE THREAD

**Issue by codewithtyler** [pullapprove/support#17]
Is it possible to check for more than one regex? In the docs the example `^Approved/g`, but I'd like to also check for `\:shipit\:/g` that way the reviewers have the option to approve using either method. Is this possible at this time? If not, then I'd like to request it be added.

**Comment by davegaeddert** [comment]
Hey @RandomlyKnighted, you should be able to accomplish that with normal regular expression behavior -- the following would check for "Approved" or ":shipit:" at the beginning of a line:

``` yaml
approve_regex: '^(Approved|:shipit:)'
```
