### ISSUE TITLE
If resetting approval status on commits, check if diff actually changed

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#2]
Not relevant yet, but worth keeping in mind:

> One pain point we found was where developers amended a pull request by squashing all commits and force pushing to their PR branch. We found that this was annoying having to go back and ask for another +1 from the team when the actual diff hadn't changed. To fix this we stored the sha256 of the complete diff along with the PR status, so that if a commit was amended but no code changed, it was automatically approved.

**Comment by cdeszaq** [comment]
Super mega 👍 for this idea. Only requiring re-approvals if the diff actually changes between pushes would _massively_ reduce overhead for those who want to keep a "clean" version history and not irritate reviewers by squashing review-driven changes along the way.

**Comment by davegaeddert** [comment]
PullApprove v3 is now based off of the built-in GitHub reviews which have their own settings and controls for dismissing reviews. More info here: https://www.pullapprove.com
