### ISSUE TITLE
Notifications when a PR is awaiting your approval

### ISSUE THREAD

**Issue by brent-hoover** [pullapprove/support#21]
If 3 out of 4 (or however you repo is configured) people have approved a PR and you are the only one left, have it send you some sort of notification. Configurable time frames for how aggressive the reminders are.

**Comment by zspoelstra** [comment]
It'd be great to have Slack integration for this as well

**Comment by jonahwh** [comment]
We've written a pretty rough cut Slack notifier for Pullapprove. [Check it out](https://github.com/giftcardzen/pullapprove-notifier).

**Comment by davegaeddert** [comment]
Thanks @crazydog115! Do you want to add just a couple sentences here about what it does / how it works?

**Comment by jonahwh** [comment]
Yeah - essentially it'll look through a list of Github repos you specify, and look for open pull requests. It'll then figure out if all status checks but pullapprove are green. If they are, it figures out who needs to approve them, and sends them a message on Slack.

It won't ping the person who created the pull request, anyone who has already approved it, or anyone who has recently commented in the pull request (how recent can be controlled by an environment variable). It also won't send a message if the person is not active on slack, or outside of configured "working hours".
