### ISSUE TITLE
Uptime and reliability

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#23]
Unfortunately PullApprove had it's first outage yesterday, albeit only for a handful of hours and a small subset of users. Nevertheless, we know that as a part of your workflow, you depend on PullApprove being up and available -- especially when it is a required status check on your repos. While we can't guarantee 100% uptime (anybody who does it probably lying), we can take steps towards preventing and handling it as best as we can.
- a new status page at http://status.pullapprove.com
- status updates via Twitter [@pullapprovestat](https://twitter.com/pullapprovestat)
- tools to assist in managing PullApprove settings in case of status checks being down (i.e. disable required status check across organization repos in 1-click)
- better error reporting internally and time to resolution
- more robust test-driven development
- and of course, extensively using PullApprove to build PullApprove ;)

**Comment by ghost** [comment]
@davegaeddert : Hi, I believe status checks for https://pullapprove.com are not working properly, 
I'm getting a 502 right now when reaching https://pullapprove.com/ and our webhooks are not working. 
Gook luck!

**Comment by davegaeddert** [comment]
@svigneux thanks for saying something! Looks like the last deployment failed to restart the web server.

We're going to take a few more steps towards automated availability monitoring and recovery!

**Comment by crstanierhf** [comment]
@davegaeddert is the status page still working. I'm getting an inactive error when visiting it.

**Comment by davegaeddert** [comment]
Hey @crstanierhf -- the status page is no longer up. We weren't doing a good enough job of keeping it up-to-date, so the only thing it was typically showing was when GitHub itself had downtime. Hopefully we will bring some version of it back so that people have a place to look, but we need to get the right systems in place first.

Instead, we've been focusing on PullApprove v3. We haven't posted this publicly yet, but it looks like some of your co-workers have already found it 😉. Here's a link if you want to look around or test it out (note: there are a few things we're still cleaning up and finishing): https://www.pullapprove.com
