### ISSUE TITLE
Deleting repo doesn't remove PR checks or webhooks

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#24]
This is a known issue with deleting repos from PullApprove. PullApprove should remove the required status check automatically. We may or may not delete the webhooks automatically (vs giving the user instruction to do so). The reason for that being that in order to do it, PullApprove would have to have the `admin:repo_hook` permission, which makes some people uneasy because it means it would have access to all of the other hooks on the repo too, not just the hook for PullApprove.

**Comment by ketiko** [comment]
I have deleted the repo from pullapprove, I've also deleted the webhooks in my repository for it.  However I'm still seeing it on my pull requests that I create.  What did I miss?

**Comment by ketiko** [comment]
Fixed it, for others that might have this issue:

Go to repo's settings page, branches, edit each protected branch and uncheck pullApprove.   You must do this in addition to removing the webhook settings.

**Comment by davegaeddert** [comment]
Ok PullApprove now automatically disables itself as a required status check. It **does not** remove the webhook, as it does not have permission to delete webhooks, but there is a message after deletion that prompts the user to do so.
