### ISSUE TITLE
Existing protected branch settings removed when repo added to PullApprove

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#26]

**Comment by jonahwh** [comment]
To elaborate: When adding Pullapprove to a repo, it seems that Pullapprove replaces all settings for protected branches. The protected branches remain, but the settings FOR those branches are replaced, rather than being appended to.

**Comment by davetapley** [comment]
+1

**Comment by gabrieljoelc** [comment]
+1

**Comment by davegaeddert** [comment]
Thank you for helping to make this a priority! PullApprove should now respect your original settings, if you have any, and just append itself as another required status check.
