### ISSUE TITLE
Request for approval rules based on GitHub labels

### ISSUE THREAD

**Issue by DarinMacRae** [pullapprove/support#27]
It would be useful if I could set up rules such that an approval would depend upon certain labels being applied to a pull request. For instance, I am currently working for a client that does security reviews of code. To make their lives easier they require that each PR have 1 or more pre-defined labels assigned to the PR. These labels make it easier when a release comes to determine whether or not the PR will require a security audit or not. The non-existence of one of these labels should prevent the PR from being merged. While I could probably shoe-horn in a new reviewer group or something like that it would be easier to just define some labels that must be present before the PR can be merged.

**Comment by davegaeddert** [comment]
@DarinMacRae how does the following fit into what you're describing?

Based on some other conversations with people, it sounds like another popular way to use labels would be to say that "if x label is present, then these people must review the PR". So in this example, if the `security-audit` label is on a PR, then @davegaeddert or @pullapprover must review it.

``` yaml
reviewers:
  required: 1
  members:
    - davegaeddert
    - pullapprover
  conditions:
    labels:
      - security-audit
```

I know that's not exactly the flow you were describing (which, if I understand it is more about approval being determined by the existence of a certain label), but does this fill the same need in a slightly different way?

**Comment by davegaeddert** [comment]
While not documented yet, a labels feature as described and illustrated in my previous comment is now live on pullapprove.com. Try it out if you're interested!

cc: @DarinMacRae

**Comment by davegaeddert** [comment]
Docs for this (and "files" and "branches" conditions) have been added here: http://docs.pullapprove.com/yaml/reviewers/

**Comment by DarinMacRae** [comment]
@davegaeddert , sorry for the delay. This is a good feature and I'm sure it will be useful but as you say it wasn't exactly what I was asking for. My client was needing a way to enforce that certain labels were applied to PRs before they could be merged. I think they are going to go about this another way so feel free to lower the priority of this or even close it if you choose. Thanks for following up.
