### ISSUE TITLE
PR in pullapprove.com dashboard showing "None" and PR status "Waiting for status to be reported"

### ISSUE THREAD

**Issue by gabrieljoelc** [pullapprove/support#32]
Repo index:
![image](https://cloud.githubusercontent.com/assets/147849/12966004/dfbfb054-d017-11e5-8aeb-ccd2690fbbe9.png)
Repo details:
![image](https://cloud.githubusercontent.com/assets/147849/12966007/e68f3a76-d017-11e5-95f4-2aa2083ad3bc.png)

**Comment by davegaeddert** [comment]
Hey @gabrieljoelc, something must have gotten cut off in the middle of syncing with github. Does it look right now? In the future you should be able to get it back on track by clicking "sync open PRs" on the repo index. Let me know if things still aren't quite right!
