### ISSUE TITLE
YAML template override reviewer settings

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#34]
Currently using `extends` and changing adding any settings for `reviewers` will **override all of the reviewer settings**. This needs to be explained in the documentation: http://docs.pullapprove.com/yaml-templates/

It may be worth considering a way to allow overriding specific settings on the reviewer group, ex. changing the `required` value without changing who the `members` are. One question here would be what happens then if you want to remove a reviewer group that was included in the template. Or remove one member specifically, or add one to the template member list...some of those may not be use cases in reality.

Sparked by this: https://github.com/BuoyantIO/linkerd/commit/153971cb19f0e98ec3fbdfe8f3aaddd158683259

**Comment by esbie** [comment]
@davegaeddert thanks for looking into this, it was unclear to me from the documentation whether property merges were possible. Agreed that addition/removal of reviewer group or member are tricky use cases, so I'm not surprised they're unsupported

**Comment by davegaeddert** [comment]
Dictionary-like YAML objects now merge in the new .pullapprove.yml `version: 2`!

http://docs.pullapprove.com/yaml-templates/

Updated docs for v2: http://docs.pullapprove.com/
Related blog post: https://blog.pullapprove.com/pullapprove-github-code-review-43761a64ea9a#.ep6609pee
