### ISSUE TITLE
GitHub usernames are case-sensitive

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [pullapprove/support#35]
GitHub users specified in the members section are case-sensitive.  GitHub's API is not case-sensitive.  Ultimately, I think the solution is to not introduce case-sensitivity, but I'm hoping for at least a callout in the docs.

For example notice [request A](https://api.github.com/users/blackbaud-bobbyearl) and [request B](https://api.github.com/users/Blackbaud-BobbyEarl) both return the same user.

**Comment by davegaeddert** [comment]
Should be case-insensitive now :+1:
