### ISSUE TITLE
Automatically approve for author

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#4]
A potential per-repo setting for automatically setting the approval status if the PR author is a reviewer (i.e. @davegaeddert created the PR, so he automatically approves of his work). Might also be scenarios where people don't want this -- sometimes a PR is created before the work is actually started/finished, so the author would know that it's not ready to merge...

**Comment by davegaeddert** [comment]
Closing this for now in favor of the decisions made in http://docs.pullapprove.com/yaml/author_approval/.

**Comment by Thalagyrt** [comment]
I'd love to see this auto option at some point in the future if you can get it in!

**Comment by davegaeddert** [comment]
This has been launched as part of .pullapprove.yml `version: 2`!

http://docs.pullapprove.com/groups/author_approval/

> Updated docs for v2: http://docs.pullapprove.com/
> Related blog post: https://blog.pullapprove.com/pullapprove-github-code-review-43761a64ea9a#.ep6609pee
