### ISSUE TITLE
Finer Grained Permissions around Adding/Removing PullApprove Integration

### ISSUE THREAD

**Issue by bka9** [pullapprove/support#43]
Currently if you are part of an organization you can add/remove repositories to/from the PullApprove integration. It would be better to at least have a tighter permissions around having the ability to remove pull approve integration from a repository to some group of users. It seems like this is a tool to help enforce policy, but if any user of an organization can remove the integration then the policy is not very strong.

**Comment by davegaeddert** [comment]
Hey @bka9, currently we require admin permission on the repo to add or remove it from PullApprove. Have you experienced something different??

We do try to match permissions as closely as possible with GitHub -- i.e. a repo admin can delete a repo on GitHub, and a repo admin can remove a repo from PullApprove
https://help.github.com/articles/repository-permission-levels-for-an-organization/

Let me know. We definitely want to get that straightened out if something is off.
