### ISSUE TITLE
Webhooks

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#48]
Especially when it comes to integrating with other services/workflows, a set of webhook events would go a long way.

Tentative events:
- when a PR is created
- when PR is successfully reviewed
- when reviewer approves/rejects
- any time PR review status changes

These would be set up in .pullapprove.yml.

**Comment by justi** [comment]
👍

**Comment by davegaeddert** [comment]
PullApprove v3 is now based off of the built-in GitHub reviews, so much of this can be done with GitHub's webhooks. More info here: https://www.pullapprove.com
