### ISSUE TITLE
Syncing does not update approval status

### ISSUE THREAD

**Issue by DavidDTA** [pullapprove/support#49]
Choosing "sync open PRs" does not update the approval status on those PRs.  The change I'm looking at shows as approved on the pullapprove website, but not on the github website.

**Comment by davegaeddert** [comment]
Hey @hospitalitarian -- I saw a few errors come through. It looks like maybe somebody's access to your org has changed? I don't see any admins that PullApprove is aware of. You can send a message through Intercom on pullapprove.com if you want to talk specifics in private -- I don't see your name showing up in Intercom at the moment.

**Comment by DavidDTA** [comment]
Yes, that's exactly what happened.  We were able to restore permissions, and it seems that write permissions are required for the account that owns the pullapprove account.
