### ISSUE TITLE
Pull requests are marked as outdated

### ISSUE THREAD

**Issue by ilyapuchka** [pullapprove/support#50]
We just integrated PullApprove to our repo and noticed that now after pull request is done each time something changes in t's target branch (for example another pull request is merged) it is marked as outdated (This branch is out-of-date with the base branch). Even if there are no actual merge conflicts. It requires to update brunch what creates just empty commit. Can it be something in PullApprove itself or is it related to some wrong setup for status checks?

**Comment by davegaeddert** [comment]
Hey @ilyapuchka, that's actually a side effect of enabling protected branches on GitHub. See bottom of this post: https://github.com/blog/2051-protected-branches-and-required-status-checks

You don't have to use protected branches to use PullApprove, it just allows you to literally prevent merging until PR's pass approval.

**Comment by ilyapuchka** [comment]
Thanks!

**Comment by davegaeddert** [comment]
Hey @ilyapuchka not sure if you saw this, but it should definitely help! https://github.com/blog/2137-protected-branches-improvements
