### ISSUE TITLE
Skip approval for changes to specific files

### ISSUE THREAD

**Issue by jessemyers** [pullapprove/support#52]
Our release workflow involves small changes to certain files to bump versions. It's feeling tedious to run through a PR/Approval for these changes, especially when we release often.

Is it possible to not require approval (or auto approve) changes that only touch certain files. I imagine this could either be implemented as `.pullapproveignore` file or as an extension to the Conditions syntax:

```
conditions:
  files:
    - !.bumpversion.cfg
    - !setup.py
```

**Comment by adamhadani** [comment]
+1

**Comment by davegaeddert** [comment]
Check out the new `exclude` field in .pullapprove.yml `version: 2`!

http://docs.pullapprove.com/groups/conditions/

```
conditions:
  files:
    exclude:
      - .bumpversion.cfg
      - setup.py
```

Updated docs for v2: http://docs.pullapprove.com/
Related blog post: https://blog.pullapprove.com/pullapprove-github-code-review-43761a64ea9a#.ep6609pee
