### ISSUE TITLE
Feature idea: opt-into even one "Rejected" to fail the status check

### ISSUE THREAD

**Issue by gabrieljoelc** [pullapprove/support#54]
The out-of-the-box functionality is more of a voting system: if 2 approvals are required and a PR has 2 approvals and one rejected, then the status check is "OK". I would like the ability to enable making the status check be "failing" if one or more team member rejects the PR even if the PR meets the required approval count (from approvals from other team members). For example, if this feature is enabled and 2 approvals are required and a PR has 2 approvals and one rejected, the status check should be "failing".

**Comment by davegaeddert** [comment]
@gabrieljoelc take a look at the `reject_value` setting: http://docs.pullapprove.com/yaml/reject_value/

**Comment by gabrieljoelc** [comment]
oh cool that should do it. missed that. thx!
