### ISSUE TITLE
Button to force-send PR status to GitHub

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#55]
If, for whatever reason, the status from PullApprove does not make it to GitHub then it's possible to get stuck in a state where PullApprove thinks it was sent successfully, and won't send a new one until that status changes. Not even clicking a "sync" button will re-send the actual status if there is no change.

Aside from preventing this from happening in the first place, we may need to add a button somewhere to send a status update to GitHub no matter what.

**Comment by zspoelstra** [comment]
We're seeing a number of approvals recently not making it to either Pull Approve or back to Github.

**Comment by davegaeddert** [comment]
Ok we added a button in the overflow menu on the pull request view. It will send whatever PullApprove's current status is back to GitHub, regardless of what GitHub has currently.

![image](https://cloud.githubusercontent.com/assets/649496/14473632/a0eba040-00be-11e6-9b64-df070c93b11c.png)
