### ISSUE TITLE
Turn status to red if rejection is stronger

### ISSUE THREAD

**Issue by ishitatsuyuki** [pullapprove/support#56]
If the total value(accept-reject)<0, turn the status into failed.

**Comment by davegaeddert** [comment]
Hey @ishitatsuyuki, you should check out the [`reject_value`](http://docs.pullapprove.com/yaml/reject_value/) setting -- what you're looking for isn't the default behavior for PullApprove, but if you set `reject_value: -1` then it should do what you want!
