### ISSUE TITLE
Approve with comment using new Github emoji

### ISSUE THREAD

**Issue by dolfelt** [pullapprove/support#57]
It appears that recently Github started using actual emoji characters instead of the strings (`:smile:`). How would we make this new way GH does emoji work for approving through comments. Here's what I have tried:

``` yaml
approve_regex: '^(:\+1:|\u1F44D)'
reject_regex: '^(:\-1:|\u1F44E)'
```

``` yaml
approve_regex: '^(:\+1:|\u{1F44D})'
reject_regex: '^(:\-1:|\u{1F44E})'
```

Please let me know how I can resolve this for my team. Thanks!

**Comment by davegaeddert** [comment]
Hey everybody, we pushed some changes out a few hours ago to deal with this. If you use emoji aliases (i.e. `:+1:`) in your regex pattern, we'll now automatically check for their unicode equivalent (i.e. `\U0001f44d`) when parsing comments for approval. **You do not need to add unicode to your regex -- whatever you were using before should now automatically work for matching either unicode or aliases.**

This was a pretty quick fix but seems to be working well so far. Let us know if you have any issues!
