### ISSUE TITLE
Intense pullapprove updates in Slack

### ISSUE THREAD

**Issue by olix0r** [pullapprove/support#58]
We have slack configured to post github comments into a channel. Recently, github started posting for comment edits.  So, when pullapprove updates a comment with a badge, we receive another update.  The duplicate notification isn't so much a problem, as much as it is the way they are rendered (with a huge logo):
<img width="978" alt="screen shot 2016-04-19 at 2 21 53 pm" src="https://cloud.githubusercontent.com/assets/240738/14656095/6b77b5f8-063a-11e6-960f-29c24bd4291c.png">

Any suggestions on how to lessen the intensity of pullapprove updates in slack?

**Comment by davegaeddert** [comment]
Hey @olix0r, we noticed the same thing. We did a little redirect-magic to remove the open graph tags in certain scenarios. If you approve some PR's in the next couple days, would you mind checking Slack and seeing if it stops adding the image? The ugly HTML will still be there for now but hopefully it doesn't try to insert the image automatically.

**Comment by olix0r** [comment]
Thanks for the quick fix! I can already see that it looks much nicer ;)

**Comment by davegaeddert** [comment]
Agreed!
