### ISSUE TITLE
Teams and YAML disappear, need re-synced from GitHub

### ISSUE THREAD

**Issue by jbhannah** [pullapprove/support#63]
We have PullApprove configured on my organization's private repo to require approvals from the `dev` team on PRs. Occasionally when I create a PR on the repo, PullApprove fails with a message that the `dev` team doesn't exist, and in the repo settings on PullApprove all teams and the YAML have disappeared and need re-synced from GitHub.

**Comment by davegaeddert** [comment]
Thanks for reporting this @jbhannah. I was talking with another customer yesterday who was having the same issue but we weren't able to figure out what exactly was causing it yet. Is that repo extending a YAML template?

**Comment by davegaeddert** [comment]
I found and fixed a bug here, thanks again. I just re-synced all of your organizations repos so things should be back to normal now. Let me know if it happens again!

**Comment by jbhannah** [comment]
Thanks! Yes, we are extending the `default` template. I'll keep an eye on it and will let you know if it happens again. :)
