### ISSUE TITLE
API

### ISSUE THREAD

**Issue by jonahwh** [pullapprove/support#64]
I'd like to see the availability of a PullApprove API. It would be convenient to be able to query an API and get a list of things such as:
- Pull Requests that need approval
- Who is needed to review each pull request

**Comment by allanhortle** [comment]
I'd also love to be able to enable PullApprove via an API. 
I've got a CLI tool to create repo's with default settings, but I still have to got a url to enable PA for the repo.

**Comment by davegaeddert** [comment]
Hi @allanhortle -- we do have a very basic API for enabling pullapprove on repos. If you log in to pullapprove.com and send us a message via Intercom, I'd be happy to give you an access token.

**Comment by davegaeddert** [comment]
The new PullApprove v3 is completely integrated with GitHub reviews -- so their API can now be used for this info! More about the new PullApprove can be found here: https://www.pullapprove.com

Also, it is a GitHub App now, so enabling repos can also be done via GitHub.
