### ISSUE TITLE
"Signed-off-by" in commit messages

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#65]

**Comment by caniszczyk** [comment]
many projects like the Linux Kernel and Docker use "Signed-off-by" in the commit message to ensure people comply with the DCO: http://developercertificate.org/

It would be great to have this enforced in PullApprove somehow that your commit messages must be signed off by the contributor(s)

**Comment by davegaeddert** [comment]
Thanks @caniszczyk, does it matter _who_ signed off? Or just that someone did?

**Comment by caniszczyk** [comment]
@davegaeddert the git-author of all the commits in the PR would be ideal 

As the author is making this assertion:

Developer's Certificate of Origin 1.1

> By making a contribution to this project, I certify that:
> 
> (a) The contribution was created in whole or in part by me and I
>     have the right to submit it under the open source license
>     indicated in the file; or
> 
> (b) The contribution is based upon previous work that, to the best
>     of my knowledge, is covered under an appropriate open source
>     license and I have the right under that license to submit that
>     work with modifications, whether created in whole or in part
>     by me, under the same open source license (unless I am
>     permitted to submit under a different license), as indicated
>     in the file; or
> 
> (c) The contribution was provided directly to me by some other
>     person who certified (a), (b) or (c) and I have not modified
>     it.
> 
> (d) I understand and agree that this project and the contribution
>     are public and that a record of the contribution (including all
>     personal information I submit with it, including my sign-off) is
>     maintained indefinitely and may be redistributed consistent with
>     this project or the open source license(s) involved.

**Comment by davegaeddert** [comment]
Hey @caniszczyk, would love to get some feedback here. I took an initial stab at this and ran the open PR's on opencontainers/runc through it to see what happened. Below are some specific questions (repo is public so I figured you wouldn't mind if I posted here).

First off, the gist of how I have this working right now is for every commit, to check that the git _committer_ signed-off on the commit. I went with committer as opposed to author because of the language in the [git commit docs](https://git-scm.com/docs/git-commit) -- "it typically certifies that committer has the rights [...]". Thoughts on this? You mentioned git-author...would you prefer it checked the author? Is there any reason to make this an option for people to decide whether they want it to check committer or author (or both)?

I was going to ask either way, but that decision did mean that https://github.com/opencontainers/runc/pull/913 would fail the check:

``` json
[
  {
    "committer": {
      "following_url": "https://api.github.com/users/georgethebeatle/following{/other_user}",
      "gists_url": "https://api.github.com/users/georgethebeatle/gists{/gist_id}",
      "organizations_url": "https://api.github.com/users/georgethebeatle/orgs",
      "url": "https://api.github.com/users/georgethebeatle",
      "events_url": "https://api.github.com/users/georgethebeatle/events{/privacy}",
      "html_url": "https://github.com/georgethebeatle",
      "subscriptions_url": "https://api.github.com/users/georgethebeatle/subscriptions",
      "avatar_url": "https://avatars.githubusercontent.com/u/9860469?v=3",
      "repos_url": "https://api.github.com/users/georgethebeatle/repos",
      "received_events_url": "https://api.github.com/users/georgethebeatle/received_events",
      "gravatar_id": "",
      "starred_url": "https://api.github.com/users/georgethebeatle/starred{/owner}{/repo}",
      "site_admin": false,
      "login": "georgethebeatle",
      "type": "User",
      "id": 9860469,
      "followers_url": "https://api.github.com/users/georgethebeatle/followers"
    },
    "author": {
      "following_url": "https://api.github.com/users/pppepito86/following{/other_user}",
      "gists_url": "https://api.github.com/users/pppepito86/gists{/gist_id}",
      "organizations_url": "https://api.github.com/users/pppepito86/orgs",
      "url": "https://api.github.com/users/pppepito86",
      "events_url": "https://api.github.com/users/pppepito86/events{/privacy}",
      "html_url": "https://github.com/pppepito86",
      "subscriptions_url": "https://api.github.com/users/pppepito86/subscriptions",
      "avatar_url": "https://avatars.githubusercontent.com/u/13659109?v=3",
      "repos_url": "https://api.github.com/users/pppepito86/repos",
      "received_events_url": "https://api.github.com/users/pppepito86/received_events",
      "gravatar_id": "",
      "starred_url": "https://api.github.com/users/pppepito86/starred{/owner}{/repo}",
      "site_admin": false,
      "login": "pppepito86",
      "type": "User",
      "id": 13659109,
      "followers_url": "https://api.github.com/users/pppepito86/followers"
    },
    "url": "https://api.github.com/repos/opencontainers/runc/commits/c5587a894ca37876803a0b871a77aa81ed629998",
    "comments_url": "https://api.github.com/repos/opencontainers/runc/commits/c5587a894ca37876803a0b871a77aa81ed629998/comments",
    "html_url": "https://github.com/opencontainers/runc/commit/c5587a894ca37876803a0b871a77aa81ed629998",
    "sha": "c5587a894ca37876803a0b871a77aa81ed629998",
    "parents": [
      {
        "url": "https://api.github.com/repos/opencontainers/runc/commits/42dfd606437b538ffde4f0640d433916bee928e3",
        "sha": "42dfd606437b538ffde4f0640d433916bee928e3",
        "html_url": "https://github.com/opencontainers/runc/commit/42dfd606437b538ffde4f0640d433916bee928e3"
      }
    ],
    "commit": {
      "committer": {
        "date": "2016-06-14T09:18:43Z",
        "name": "Georgi Sabev",
        "email": "georgethebeatle@gmail.com"
      },
      "author": {
        "date": "2016-06-10T10:35:13Z",
        "name": "Petar Petrov",
        "email": "pppepito86@gmail.com"
      },
      "url": "https://api.github.com/repos/opencontainers/runc/git/commits/c5587a894ca37876803a0b871a77aa81ed629998",
      "tree": {
        "url": "https://api.github.com/repos/opencontainers/runc/git/trees/7945660185b8c70b1ceb8e8bf0ff34ba12df90d1",
        "sha": "7945660185b8c70b1ceb8e8bf0ff34ba12df90d1"
      },
      "comment_count": 0,
      "message": "Allow additional groups to be overridden in exec\n\nSigned-off-by: Julian Friedman <julz.friedman@uk.ibm.com>\nSigned-off-by: Petar Petrov <pppepito86@gmail.com>"
    }
  }
]
```

The other issue I suspected and found on https://github.com/opencontainers/runc/pull/860 is figuring out a good way to check that the specific person did in fact sign-off in the commit message. Currently, I'm using the `commit['committer']['email']` field, which won't work if the user signed-off with a different email address... What would your course of action be here? My first thought would be to ask the user to re-sign-off with the "correct" email address...

``` json
[
  {
    "committer": null,
    "author": null,
    "url": "https://api.github.com/repos/opencontainers/runc/commits/2e024709793547fd9350bcd98e8f3a769d0aa35f",
    "comments_url": "https://api.github.com/repos/opencontainers/runc/commits/2e024709793547fd9350bcd98e8f3a769d0aa35f/comments",
    "html_url": "https://github.com/opencontainers/runc/commit/2e024709793547fd9350bcd98e8f3a769d0aa35f",
    "sha": "2e024709793547fd9350bcd98e8f3a769d0aa35f",
    "parents": [
      {
        "url": "https://api.github.com/repos/opencontainers/runc/commits/fa5ce1e2d0efe822bbb04fe9a178fdefaeba412c",
        "sha": "fa5ce1e2d0efe822bbb04fe9a178fdefaeba412c",
        "html_url": "https://github.com/opencontainers/runc/commit/fa5ce1e2d0efe822bbb04fe9a178fdefaeba412c"
      }
    ],
    "commit": {
      "committer": {
        "date": "2016-05-31T08:01:04Z",
        "name": "ben",
        "email": "ben.gray@bskyb.com"
      },
      "author": {
        "date": "2016-05-31T08:01:04Z",
        "name": "ben",
        "email": "ben.gray@bskyb.com"
      },
      "url": "https://api.github.com/repos/opencontainers/runc/git/commits/2e024709793547fd9350bcd98e8f3a769d0aa35f",
      "tree": {
        "url": "https://api.github.com/repos/opencontainers/runc/git/trees/b5d7f05fd2faebc9d85d3d325a663265a7fe1af6",
        "sha": "b5d7f05fd2faebc9d85d3d325a663265a7fe1af6"
      },
      "comment_count": 0,
      "message": "Set the 'cpu.rt_runtime_us' and 'cpu.rt_runtime_us' values of the cpu cgroup\nbefore trying to move the process into the cgroup.\n\nThis is required if runc itself is running in SCHED_RR mode, as it is not\npossible to add a process in SCHED_RR mode to a cgroup which hasn't been\nassigned any RT bandwidth. And RT bandwidth is not inherited, each new\ncgroup starts with 0 b/w.\n\nSigned-off-by: Ben Gray <ben.r.gray@gmail.com>"
    }
  },
  {
    "committer": null,
    "author": null,
    "url": "https://api.github.com/repos/opencontainers/runc/commits/41e0be6157baaa7482925ebc978a3c097fc123c9",
    "comments_url": "https://api.github.com/repos/opencontainers/runc/commits/41e0be6157baaa7482925ebc978a3c097fc123c9/comments",
    "html_url": "https://github.com/opencontainers/runc/commit/41e0be6157baaa7482925ebc978a3c097fc123c9",
    "sha": "41e0be6157baaa7482925ebc978a3c097fc123c9",
    "parents": [
      {
        "url": "https://api.github.com/repos/opencontainers/runc/commits/2e024709793547fd9350bcd98e8f3a769d0aa35f",
        "sha": "2e024709793547fd9350bcd98e8f3a769d0aa35f",
        "html_url": "https://github.com/opencontainers/runc/commit/2e024709793547fd9350bcd98e8f3a769d0aa35f"
      }
    ],
    "commit": {
      "committer": {
        "date": "2016-06-06T10:29:22Z",
        "name": "ben",
        "email": "ben.gray@bskyb.com"
      },
      "author": {
        "date": "2016-06-06T10:29:22Z",
        "name": "ben",
        "email": "ben.gray@bskyb.com"
      },
      "url": "https://api.github.com/repos/opencontainers/runc/git/commits/41e0be6157baaa7482925ebc978a3c097fc123c9",
      "tree": {
        "url": "https://api.github.com/repos/opencontainers/runc/git/trees/fa1bc6d92802d362d30f241a0446e5e784a9c5dd",
        "sha": "fa1bc6d92802d362d30f241a0446e5e784a9c5dd"
      },
      "comment_count": 0,
      "message": "Set the 'cpu.rt_runtime_us' and 'cpu.rt_runtime_us' values of the cpu cgroup\nbefore trying to move the process into the cgroup.\n\nRe-work of previous change to make the code unit-testable, also added a\nnew unit-test for the change.\n\nThis is required if runc itself is running in SCHED_RR mode, as it is not\npossible to add a process in SCHED_RR mode to a cgroup which hasn't been\nassigned any RT bandwidth. And RT bandwidth is not inherited, each new\ncgroup starts with 0 b/w.\n\nSigned-off-by: Ben Gray <ben.r.gray@gmail.com>"
    }
  }
]
```

Thanks for taking the time, I don't use this feature in my workflow so I'd really like to get the opinion of someone who does.

**Comment by davegaeddert** [comment]
You're welcome to try this out too if you'd like, it is actually already functional as described above (docs in https://github.com/pullapprove/support/pull/74).

**Comment by davegaeddert** [comment]
@caniszczyk any interest in providing any more input here? I'm happy to push forward without, just thought you might have an opinion or two worth hearing.

**Comment by caniszczyk** [comment]
oh sorry, completely missed this, it should be the author as the Developer Certificate of Origin (DCO: http://developercertificate.org/) implies author, not committer IMHO.

> My first thought would be to ask the user to re-sign-off with the "correct" email address...

This is the right answer :)

**Comment by caniszczyk** [comment]
@davegaeddert I will start testing this in opencontainers.org and see how it works, will report back

**Comment by caniszczyk** [comment]
> I went with committer as opposed to author because of the language in the git commit docs -- "it typically certifies that committer has the rights [...]". Thoughts on this? 

This is wrong as it's the author who is the author of the contribution. The committer simply committed the commit :)

For us to use this, we would need the author email(s) to be checked to see if they Signed-off-by to agree with the DCO

**Comment by davegaeddert** [comment]
@caniszczyk thanks. I changed it to check the author instead, that's what I needed to hear! The whole PR interface on pullapprove.com is currently in the middle of a redesign, and we'll try to factor this in, but for now you'll just see a simple list of the commit that are not signed-off:
![image](https://cloud.githubusercontent.com/assets/649496/16626315/ece58f46-436d-11e6-9849-01a68ec78375.png)

Give it a try and let me know how it goes.

P.S. thanks for mentioning PullApprove on HN ;)

**Comment by duglin** [comment]
Just curious, and this is actually more of a question about integrating with github, but is it possible to have pullapprove add comments and labels to PRs?  For example, I really like that you're adding a DCO check but it would be even better if it could not just fail the checks but also (optionally) add a comment to the PR (with a @author) so that the author can be notified that they forgot to sign it. Right now if they don't happen to manually check the PR then they may not notice for a while that they messed up - or it requires someone else to nag them.

Additionally, if there could be an option to add a label (e.g. "no-dco" - configurable) so that tooling can easily discover PRs that are missing DCOs, or so that it stands out more at the top of the PR rather than hidden in the checks section at the bottom, then that would be helpful too.

**Comment by davegaeddert** [comment]
Good question @duglin. Both are certainly possible. We actually have functionality for a bot that makes comments, just haven't released it publicly. We're still nailing down some details there regarding when it should comment and how configurable aspects of it need to be. It would be very easy though to add a mention to the author, letting them know that the commits aren't signed off. I would love to get that finalized and rolled out...

Labels I'm a little less sure about, but would definitely be possible. People have asked about having PullApprove add/remove labels related to other features. We're still considering adding that kind of functionality, just want to make sure it can be done simply and straightforward-ly. 

Couldn't help myself -- looks like you've done some stuff with Travis checking DCO. Are you considering using PullApprove to handle that instead?

**Comment by duglin** [comment]
Yes, I would love to get rid of my .validateDCO thingy and just use pullapprove !

**Comment by davegaeddert** [comment]
Great! Well I'm not sure if @caniszczyk has actually had a chance to try this or not (@caniszczyk, let me know if you have any further feedback) but I'm going to merge it into the official documentation as-is for now.

I would like to keep the conversation going regarding comments and labels, just in #81 and #46 instead of here.

Feel free to give this a try and let me know how it goes!

``` yaml
signed_off_by:
  required: true
```

http://docs.pullapprove.com/yaml/signed_off_by/

**Comment by duglin** [comment]
hmm does it only check for a DCO after a LGTM?
See:  https://github.com/cncf/servicebroker/pull/16
As a reviewer I don't want to even bother looking at a PR w/o a DCO so I'd like to be checked first.

**Comment by davegaeddert** [comment]
@duglin it will run the checks at the same time (for approvals and DCO) but it pulls config from master so your .pullapprove.yml will need to be merged in first. Otherwise people could change the settings to merge in their PR, etc.

**Comment by duglin** [comment]
ok. right now i don't have anything in master - so is it just using a default .pullapprove.yml ?

**Comment by davegaeddert** [comment]
Yeah, could be a little more clear but by default the person who set it up is the only reviewer. When you add a repo there should be a thing at the top of the page with a suggested .pullapprove.yml -- that's also what the settings are if you don't have a .pullapprove.yml.

**Comment by davegaeddert** [comment]
Working on a new onboarding flow as well ;)

**Comment by duglin** [comment]
<img width="566" alt="screen shot 2016-07-15 at 6 44 52 pm" src="https://cloud.githubusercontent.com/assets/1944671/16890401/3d79e2fe-4abc-11e6-8ff2-bdd48c39ab00.png">

https://github.com/cncf/servicebroker/pull/18

It appears to be working however is it possible to make it report a failure instead of pending? As it is now I suspect people will look at it and ignore it thinking that the system is waiting on something to happen - either by a person or my the CI stuff.  But a big red X will be clear that the PR author probably messed up and then they'll look at it.

**Comment by duglin** [comment]
so instead of "Approval required by duglin; "Signed-off-by" n..." having it just say:
 `X "Signed-off-by" is missing`
would be great

**Comment by davegaeddert** [comment]
I'm good with that...mostly listening to you guys in terms of how this fits into your workflow. I went back and forth on it originally, but a rejected status makes sense to me. I just updated your test PR -- should make it feel much more like a requirement now!

**Comment by duglin** [comment]
@davegaeddert excellent!!! thanks so much!
