### ISSUE TITLE
Editing other people's comments lets you approve/reject PRs for them.

### ISSUE THREAD

**Issue by jonahwh** [pullapprove/support#69]
If someone other than you leaves a comment on a pull request, a repo admin can edit the comment and add the approve/reject string to it. This causes PullApprove to think the original author approved or rejected the PR.

It seems there is a `sender` object in the webhooks that can be keyed off, if it is populated by the User that edited the comment, not the user who made the original comment.

**Comment by davegaeddert** [comment]
Hey @crazydog115 thanks for pointing this out. Unfortunately the `sender` object refers to the original commenter (at least from what I can tell). If you want to verify that though, I'd appreciate it -- easiest way is to just go into settings > webhooks and click one of the hooks that would have received that event (like PullApprove) and look at the JSON that it sent.

**Comment by jonahwh** [comment]
Just tried it - the `sender` was me, but the `comment.user` was the original author.

**Comment by davegaeddert** [comment]
Sure enough. I knew that didn't seem right...not sure what I was looking at before. So what are you thinking here? That only the original author should be able to change their approval by editing their comments? Have you had issues with admins editing other people's comments to change their approval?

**Comment by jonahwh** [comment]
I haven't had any issues with it, it just seems like a small security issue that's easy enough to patch. I don't think anybody but the original author should be able to modify their own statuses.

**Comment by davegaeddert** [comment]
I like the general policy of not allowing a user to change another user's review status (although a repo admin could circumvent it in a bunch of other ways). Edited/deleted comments now only modify the status if it was edited/deleted by the original author.
