### ISSUE TITLE
Not seeing any of my org repos to add

### ISSUE THREAD

**Issue by abendy** [pullapprove/support#7]

**Comment by davegaeddert** [comment]
Hey @abendy, does the organization not show up as a tab across the top (on the https://pullapprove.com/choose-repo/ page)? If you have access to them on github.com, then they should be showing up unless they have already been added to PullApprove.

**Comment by abendy** [comment]
@davegaeddert no org tabs, just my own username

**Comment by davegaeddert** [comment]
@abendy have your organizations given access? If you go to https://github.com/settings/applications, and find PullApprove, there should be a section for "Organization access" at the bottom.

**Comment by abendy** [comment]
@davegaeddert needed to re-auth PA. The org is very recent so it was probably created after the initial auth. Thanks
