### ISSUE TITLE
Support for GitHub multiple assignees

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#71]
https://github.com/blog/2178-multiple-assignees-on-issues-and-pull-requests

**Comment by DavidPoliakoff** [comment]
Neat! Commenting to keep informed, and be sure to ping if you want a friendly beta tester

**Comment by cdeszaq** [comment]
This is a duplicate, or extension, of #39

**Comment by davegaeddert** [comment]
See #39, but closing with the new PullApprove v3 in mind (https://www.pullapprove.com).
