### ISSUE TITLE
Team is not recognized unless it's associated to a repository

### ISSUE THREAD

**Issue by ishitatsuyuki** [pullapprove/support#72]
The title says most of the problem. Additionally, it shows the error like the YAML is the problem, however it can be solved by making the system recognize the team.

**Comment by davegaeddert** [comment]
Thanks for pointing this out. Currently we check the repo teams endpoint on the GitHub API when matching with your YAML -- https://developer.github.com/v3/repos/#list-teams. It seems that only teams given explicit access (in repo settings on github.com) show up in this list although there may be other ways now that they could have been given access.

**Comment by nikoargo** [comment]
I'm using nested teams, and the nested teams didn't show up in the PullApprove interface until I added them explicitly to the repo. Having the parent team listed wasn't enough.

**Comment by davegaeddert** [comment]
Good to know. Looks like the nested teams API is in preview still -- once it's out of preview then it should work fine without adding them directly.

**Comment by davegaeddert** [comment]
The new PullApprove v3 is completely built around GitHub's official review system -- so we follow whatever rules they do now in terms of who can review.

More info here: https://www.pullapprove.com

**Comment by nikoargo** [comment]
Thanks! I'm excited to check it out!
