### ISSUE TITLE
Improve flow in the case of configuration error

### ISSUE THREAD

**Issue by Shredder121** [pullapprove/support#77]
Currently we're in a bit of a pickle:

We have set up PullApprove, but our configuration (highly influenced by the configuration in the documentation) is not correct.
https://github.com/querydsl/querydsl/pull/1957

However, now we're stuck with a failing status check.

Just wanted to hear some feedback on how or whether you meant this to work.

![Failing code review](https://cloud.githubusercontent.com/assets/4105066/16568361/7ebed170-4229-11e6-84c4-89a74f248c69.png)

**Comment by davegaeddert** [comment]
Hey @Shredder121, good question. There could/should certainly be a better flow for notifying you of YAML issues, ideally _before_ they get committed so you don't get stuck in the situation you're in. Some services, like Travis, have a [linter/validator](https://docs.travis-ci.com/user/travis-lint) which seems ok. A step further which I think would be helpful would be for PullApprove to automatically check if a PR is making changes to `.pullapprove.yml`, and to build that into the status check -- giving an error status if the new YAML will be invalid if merged. That would obviously only work if you edited `.pullapprove.yml` through a PR...

Thoughts on that? Or do you have ideas about how it would work ideally from your perspective?

Also, let me know if you think there are any specific examples in the docs that are incorrect...

**Comment by Shredder121** [comment]
> There could/should certainly be a better flow for notifying you of YAML issues, ideally _before_ they get committed

Haha yes exactly, that's why I opened up this ticket.

> A step further which I think would be helpful would be for PullApprove to automatically check if a PR is making changes to `.pullapprove.yml`, and to build that into the status check -- giving an error status if the new YAML will be invalid if merged.

I think that is indeed a good way of going about this.
Do you think that a separate status context would be good for that?
It doesn't clutter the UI too much and you don't need to cram multiple messages in one status text.

A separate linter tool could also work, but having immediate feedback on the actual result is also very good.
So I don't mind having either one or the other, although playing with the YAML before using PullApprove might also be a valid use case.

**Comment by davegaeddert** [comment]
Sounds good. I'll see if we can get something figured out. I hadn't actually thought about using separate status contexts for different purposes, I'll give that some thought too.

**Comment by Shredder121** [comment]
> Also, let me know if you think there are any specific examples in the docs that are incorrect...

Sorry, I didn't mean that there are any incorrect examples.
I meant that even when referring back to the documentation and compose your configuration, subtle things like what type the configuration elements are can accidentally be looked over.
But now that I am here:

The new repo screen uses for the example YAML unquoted regexes.

![new repo](https://cloud.githubusercontent.com/assets/4105066/16569399/3d40f158-4236-11e6-9d71-64c8290d54f0.png)

I know it _should_ be valid, but in the documentation you always use single quotes.
Moreover, looking at the documentation it _looks like_ it's even required/recommended.

> Possible values: any valid regex, in a _single-quoted_ string

**Comment by davegaeddert** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;6NL5nhfX&#x2F;10-yaml-validation-in-pr"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> YAML validation in PR</a>

**Comment by Shredder121** [comment]
Should I not be able to see that?
Just asking.

**Comment by davegaeddert** [comment]
Nope, sorry. Didn't know it would make a comment here.

Thanks for pointing out the quotes. You're right -- I _do_ recommend using single-quotes for the regexes and the YAML output there is how PyYAML dumps it out.

**Comment by 9len** [comment]
big +1 to doing something here. I found it deeply ironic that setting up a tool to enforce code review required multiple, untestable hand-commits to master.

**Comment by davegaeddert** [comment]
Thanks for pushing on this, new code was just deployed to add additional checks and UI for PR's that contain modifications to .pullapprove.yml. You'll now get a rejected status if the PR contains an invalid YAML, and you can go to pullapprove.com to see what the specific errors are. The PR screen on pullapprove.com is currently being redesigned so the pieces will probably shift around a little bit and hopefully look a little better ;)

![image](https://cloud.githubusercontent.com/assets/649496/16780998/c3ca25a6-483e-11e6-92be-ec7643d2e141.png)

Let me know if you have any other feedback here -- I'll close the issue for now.

**Comment by Shredder121** [comment]
Could the "Parsing errors" panel maybe go underneath, or outside the "new settings"?
Then the two blocks of configuration line up at least.

**Comment by davegaeddert** [comment]
@Shredder121 I'm going to leave it as-is for now -- if there are errors I'm ok with them being front and center. I'll play around with it though in the new design.
