### ISSUE TITLE
Group permission to approve without other groups?

### ISSUE THREAD

**Issue by kwonoj** [pullapprove/support#79]
I'm not sure if I miss in docs already available, please correct me freely.

for example let's say there are 2 groups,   

```
- group 'master'
  user : A, B
  required: 1

- group 'normal'
  user : C, D
  required: 2
```

if user A or B in `master` approves, PR immediately being approved. or PR need to be approved by C & D both. Is it possible to configure in this way?

**Comment by davegaeddert** [comment]
@kwonoj you're not missing anything! That's currently not possible, but an interesting question. I'll admit, I'm not sure off the top of my head what that would look like in YAML. Do you have a suggestion for how you might accomplish what you're looking for?

**Comment by kwonoj** [comment]
> I'm not sure off the top of my head what that would look like in YAML. Do you have a suggestion for how you might accomplish what you're looking for?

Honestly, me neither. I was came to thought of this to introduce pullapprove into one of github repo I'm contributing with above requirement, was curious if there's something already built in. Easiest idea that I can think of immediately is introducing one boolean flag can be specified into group, allows that group overrides / ignores other group approval requirements but not sure if it's extensible scheme.

**Comment by TansyArron** [comment]
```
- group 'groupA'
  user : A, B
  required: 1

- group 'groupB'
  user : C, D
  required: 2
```

I think this is possible through naming the context you send to github as follows:

If groupA conditions are true you would send to github something like:

```
{
  "state": "pending",
  "target_url": "https://example.com/build/status",
  "description": "review required from 1 of: <groupA members list>",
  "context": "pullApprove/groupA"
}
```

If groupB conditions are also true, you can send a second update:

```
{
  "state": "pending",
  "target_url": "https://example.com/build/status",
  "description": "review required from 1 of: <groupB members list>",
  "context": "pullApprove/groupB"
}
```
and so on.

There is a bit more to it, especially with requiring configuring github to require the checks - In the case that groupA requirements were not met, but `pullApprove/groupA` is a required check in github, you would need to send something like:
```
{
  "state": "success",
  "target_url": "https://example.com/build/status",
  "description": "No groupA auditor required",
  "context": "pullApprove/groupA"
}
```
The Jenkins Github plugin uses this structure already, it looks like this:

![This is what multiple contexts looks like (via the jenkins github plugin)](https://cloud.githubusercontent.com/assets/3494066/26659822/586f6d92-4663-11e7-8961-8e95598c70ab.png)

I think this modification would make PullApprove HUGELY more useful. It also allows more useful status messages - `code-review/pullapprove requires review by 1 of userA, userB, use...` is less readable than `PullApprove/Translations requires review by 1 of <userA, userB, user...`

**Comment by davegaeddert** [comment]
I think that this could probably be solved with the new phased-reviews / group conditions in v3. Feel free to take a look! https://www.pullapprove.com/docs/phased-reviews/
