### ISSUE TITLE
http://docs.pullapprove.com/yaml/reviewers/ is empty

### ISSUE THREAD

**Issue by duglin** [pullapprove/support#83]
there appears to be an issue with the docs.  http://docs.pullapprove.com/yaml/reviewers/ doesn't show anything - at least for me. I tried on FF and Chrome on a mac.

**Comment by davegaeddert** [comment]
Very strange. Mind taking a screenshot if you get the chance?
![image](https://cloud.githubusercontent.com/assets/649496/16896030/f1f73a34-4b4c-11e6-8e15-27ec5a4c45fc.png)

**Comment by duglin** [comment]
<img width="990" alt="screen shot 2016-07-16 at 4 18 35 pm" src="https://cloud.githubusercontent.com/assets/1944671/16896946/096f4840-4b71-11e6-9140-1bc36f57fd0c.png">

**Comment by duglin** [comment]
on a side note.... when I try to go to pullapprove.com it takes me to https://pullapprove.com/cncf/servicebroker/ instead of your main page like I wanted. I kind of understand why, but when I want to get to your main page I can't see to do it  :-)   I guess logging out will do it, but not sure I want to do that.

**Comment by duglin** [comment]
ha - I didn't scroll down - the text is below the menu, not to the right.  When I maximize the window then it appears on the right. What's odd is that I only have this issue in FF and Chrome, Safari shows it ok. I think the screen shots are what's doing it.  oh well, I'll close this since its just a formatting issue, not missing text.
