### ISSUE TITLE
Repo team sync requires organzation admin

### ISSUE THREAD

**Issue by jaymecd** [pullapprove/support#85]
Hi PullApprove,

> https://pullapprove.com/foodpanda/shop-new/sync-teams/ => HTTP 500,
> Uh oh. There was a problem, we're looking into it. In the meantime, try refreshing.

This issue initially was reported as part of https://github.com/pullapprove/support/issues/80#issuecomment-233081681

Thank you.

**Comment by jaymecd** [comment]
Sync everything within a repository - does not solve the problem.
@pullapprover need your support.

**Comment by davegaeddert** [comment]
@jaymecd it's not going to work without at least 1 organization admin giving access to pullapprove. You have secret teams tied to that repo (which causes similar problems to what I mentioned might happen in #80) and pullapprove can not reliably get the list of team members from the GitHub API without an org admin token. Without knowing who the members are, we can't use those teams for anything.

**Comment by jaymecd** [comment]
Understood, but i'm dealing right now with `public` team of organization.
So same fix from #80 should be applied at some point, isn't it?

Also, I was not able to find a way to reset GitHub token. Any hint on this?

**Comment by davegaeddert** [comment]
I shuffled some things around and now it has similar behavior -- meaning that if no org admin token is available, it will not allow you to use any secret teams in pullapprove for that repo. There's no visible messaging at this point to communicate that though...

Not sure what you mean by a way to "reset" a GitHub token. You can mess with your OAuth tokens here: https://github.com/settings/applications
