### ISSUE TITLE
Support labeling PRs

### ISSUE THREAD

**Issue by duglin** [pullapprove/support#86]
Couldn't find an exact match in an existing issue, but here's the use case....
- I have a repo with a list of maintainers
- but the repo is public so anyone can look at and work on the issues
- however, non-maintainers can't assign issues to themselves
- docker solves this by have a bot that looks for a "#dibs" comment and then the "assigned" label is added to the issue so that no one else grabs it.

It would be nice if there were a way in PA to enable this.  Perhaps even more generically - such as "a matching regex causes a label to be added (or removed)".

Bonus points - add a tag to the comment with the regex so it stands out

**Comment by davegaeddert** [comment]
This is a pretty old issue... but I think this kind of thing would probably best be solved these days with a specific bot (like as was mentioned for docker) for that purpose. It's a little bit outside of what we see PA doing right now (the new v3 especially).
