### ISSUE TITLE
Not accepting approval for developers group 

### ISSUE THREAD

**Issue by manjitkumar** [pullapprove/support#87]
I have got all the required approval for my pull request and it and pull approval hooks still asks for another approval from my developer group. Can you guys please help me with that. Please let me know if any other information is required on this issue.

Attached screen-shot.
<img width="687" alt="screen shot 2016-07-29 at 10 19 31 pm" src="https://cloud.githubusercontent.com/assets/5033349/17256452/36a36b9c-55db-11e6-8fa3-48e8125e3dfc.png">

**Comment by davegaeddert** [comment]
@manjitkumar sorry for the delay. You may have figured this out already but it looks like you've got `author_approval: ignored` and cdax is the author, so his approval doesn't count. Working on UI to make sure it's more clear what is happening...

**Comment by manjitkumar** [comment]
Oh Right. I got it. Thanks @davegaeddert.
