### ISSUE TITLE
Require approval for new files only

### ISSUE THREAD

**Issue by michaelcullum** [pullapprove/support#92]
Having a files filter where it would only apply to new files in a directory instead of all changes.

Rationale:
- You have a directory within which you have a series of files.
- You give each team access to review one or two of these files.
- You wish to have an admin team to review new files being added
- You do not wish your admin team to have to review all PRs to file changes in that directory.

**Comment by davegaeddert** [comment]
This can be done now in the new v3 conditions: https://www.pullapprove.com/docs/config/conditions/

You could use the `files.added` variable to check whether the PR adds files or not.
