### ISSUE TITLE
Add `always_approved`

### ISSUE THREAD

**Issue by davegaeddert** [pullapprove/support#93]
Add an `always_approved` setting that works like [`always_pending`](http://docs.pullapprove.com/yaml/always_pending/) or [`always_rejected`](http://docs.pullapprove.com/yaml/always_rejected/). The main use case being somebody makes some small insignificant changes (typo fix, etc.) and are confident that they don't need a review. There could be a label that they put on the PR so that they don't have to bug people for a review.

**Comment by JonasHaouzi** [comment]
👍

**Comment by davegaeddert** [comment]
This has been launched as part of .pullapprove.yml `version: 2`!

http://docs.pullapprove.com/groups/always_approved/

> Updated docs for v2: http://docs.pullapprove.com/
> Related blog post: https://blog.pullapprove.com/pullapprove-github-code-review-43761a64ea9a#.ep6609pee
