### ISSUE TITLE
Require changes to specific files

### ISSUE THREAD

**Issue by cdeszaq** [pullapprove/support#96]
It would be nice to require a PR has a change to a specific file (CHANGELOG in our case) in order to be approved. Not all changes would need it, so ideally a comment on the PR could override that check to turn it off for that PR, but better to overly require it than under-require it.

**Comment by davegaeddert** [comment]
@cdeszaq that's an interesting use case we haven't heard before. We'll give some thought as to how that might actually work if we were to try and do something there...

**Comment by davegaeddert** [comment]
I think that this is probably best off being a specific GitHub App, maybe built with probot (https://probot.github.io/). There may even be one that already exists. PullApprove v3 is refocused on the human aspect of PR review, and this feels more like a kind of CI check that could happen alongside it?
