### ISSUE TITLE
Allow to grant approval rights to somebody who does not have access to the repository.

### ISSUE THREAD

**Issue by michael-berlin** [pullapprove/support#97]
My colleague tried to add a GitHub user to our `members` list who doesn't have (write) access to our repository.

He said that pullapprove didn't allow this change.

Can you please support this use case as well?

More details why we're doing this:

Everybody in the project uses a "-bot" user (e.g. "enisoc-bot" instead of "enisoc") for Reviewable.io. This way we work around the fact that GitHub permissions are too coarse and we cannot give third-party applications permissions to e.g. comment on pull requests without handing out full write access. Therefore, we use the dedicated "-bot" users.

Our PullApprove config: https://github.com/youtube/vitess/blob/master/.pullapprove.yml
(Currently, I've added my bot user "mberlin-bot" and it doesn't seem to work.)

Thanks!

**Comment by michael-berlin** [comment]
I've removed my bot user again because otherwise PullApprove fails the check with the error:

```
              — Invalid .pullapprove.yml, check pullapprove.com for details
```

**Comment by davegaeddert** [comment]
Hey @michael-berlin, I think I understand your issue and will definitely give it some thought. In the meantime, I'm guessing that if you add your bot(s) as collaborators to the repo (in GitHub repo settings) then things will work. The reason being that currently we check the GitHub API repo collaborators endpoint for the list of users who can potentially be reviewers. https://developer.github.com/v3/repos/collaborators/#list-collaborators

Let me know if that doesn't solve your problem for now.

**Comment by davegaeddert** [comment]
Forgot to mention, even just read access should be fine and allow you to make that user a reviewer.

**Comment by michael-berlin** [comment]
Thanks Dave. That sounds like a good workaround. I'll try out the collaborator read access and see how that goes :)

**Comment by michael-berlin** [comment]
Update: The workaround is working for us! Thanks.
