### ISSUE TITLE
Add support for github inline reviews

### ISSUE THREAD

**Issue by marvin-bitterlich** [pullapprove/support#98]
Github now added it's own review process. 

While I didn't have the time to check it out that much I noticed that these reviews are not recognized as approvals/rejections. 

They could be uses as an alternative to regex parsing of all comments

**Comment by davegaeddert** [comment]
Thanks for putting this in here. We're working on figuring out exactly how pullapprove might integrate with the new GitHub reviews, but it's going to take a little bit of time as there's no API yet for that new feature. We'll let you know when we know more!

**Comment by davegaeddert** [comment]
Looks like there are now webhook events for reviews, no word on an API yet but we'd be able to start with this at least: https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent

**Comment by davegaeddert** [comment]
Good news -- PullApprove now reacts to the GitHub webhook events for reviews. Right now they only tell us two things:
1. When an "approved" review is submitted
2. When a review "requesting changes" is submitted

Those will then translate into approve/reject in PullApprove.

It does not:
- look for approve/reject regex's in your review comment
- put the PullApprove badge on your review comment to indicate a change in PullApprove status (no API to do this yet)
- support "dismissing" reviews in GitHub (no event for this yet)
- retroactively translate GitHub reviews into PullApprove approvals (no API to do this yet)

GitHub review integration is enabled by default but can be disabled if need be:

``` yaml
group_defaults:
  github_reviews:
    enabled: false
```

Deeper integration is on the way as soon as GitHub releases an API!

**Comment by davegaeddert** [comment]
Forgot to mention that you must be using .pullapprove.yml `version: 2`.

**Comment by simonbasle** [comment]
note that a preview API has been announced: https://developer.github.com/changes/2016-12-14-reviews-api/

**Comment by davegaeddert** [comment]
The new PullApprove v3 is completely rebuilt as a GitHub App and is completely integrated with GitHub reviews. More info here: https://www.pullapprove.com
