### ISSUE TITLE
Migrating to v2 broke our approve_regex

### ISSUE THREAD

**Issue by marvin-bitterlich** [pullapprove/support#99]
We are currently not able to approve a pr by github comment.

See on this pr that it does not work: https://github.com/Minecolonies/minecolonies/pull/168

See this pr for our previous .pullapprove.yml https://github.com/Minecolonies/minecolonies/pull/158/files

We tried the regex with a starting ^ and without it, and it does not match comments like ":+1:" or ":shipit:"

**Comment by davegaeddert** [comment]
Thanks @Kostronor, we found a bug with using author_approval `auto`. Should be fixed now and I ran that last comment through again and the approval was triggered.
